'use strict';const _Ba=_Sf.extension.getBackgroundPage();_1i=_Ba._1i;const _0t="chrome://extensions/?id="+_np;
_xg.add({reviews:_xg.chromeWS+_np+"/reviews",faq:_5y+"faq",triggers:_5y+"triggers",actions:_5y+"actions",mruTabs:_5y+"switch-to-last-used-tab-in-chrome",installer:_5y+"files/"+_pr,natComp:_5y+"native-component",tbBtns:_5y+"custom-toolbar-buttons",domTabs:_5y+"sort-group-close-tabs-by-domain",actMenu:_5y+"action-menus",relseRam:_5y+"release-ram-without-closing-tabs",chromeBugs:_5y+"chromium-bugs",updHist:_5y+"update-history",scrtDoc:_5y+"scripting",omboxShrt:_5y+"address-bar-shortcuts",mseHvrShrt:_5y+
"hover-sensitive-shortcuts",donate:_5y+"donations",winSecExcl:"https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security",fileAcc:_0t+"#:~:text=Allow%20access%20to%20file%20URLs",incogAcc:_0t+"#:~:text=Allow%20in%20Incognito"});function _Qy(){let a=[];for(let [b,c]of _Ba._Vw)a.push([b,c.name]);return a}
let _ys=_qf(function*(a){let b=yield _9d("/permns");return a.map(c=>`<c h=/permns/${c}/1>${b[c][0]}</c>`).join("")}),_Ih=_qf(function*(a,b,c){let d=yield g=>_Sf.permissions.getAll(g),e={bkm:"bookmarks",ses:"sessions",bg:"background",notf:"notifications",dwld:"downloads",hst:"<all_urls>"},f={},h=[],l;"string"==typeof a&&(a=a.trim().split(/\s+/));for(let g of a){a="hst"==g?"origins":"permissions";let k=e[g];0>d[a].indexOf(k)&&("bg"!=g||c?(_ng(f,a,[]).push(k),h.push(g)):l=!0)}c=!0;if(!_7p(f)){let g=
`${yield _9d(b)} <permReqLst>${yield _ys(h)}</permReqLst>`;yield k=>_2(g,{},k);b=Date.now();(c=yield k=>_Sf.permissions.request(f,k))&&100>Date.now()-b&&(yield _Rs("The permissions had already been granted. <hr b=2> All's well now.",1200).onShow,yield _Fy(500))}l&&_Sf.permissions.request({permissions:["background"]});return c});function _rt(a={}){_8j(a,b=>{_Sf.permissions[b?"request":"remove"]({permissions:["background"]},_pd)})}
function _Og(a){a.trigActList||(a.trigActList={});a.mouseGest||(a.mouseGest={});var b={};let c={};for(let [,,d]of _2t(a.trigActList))if("openMenu"==d.action&&_kd(d.params,"menuId")in _Ba._tt.menuSpec)b[d.params.menuId]=_Ba._tt.menuSpec[d.params.menuId];else if("saveUrl"==d.action||"saveElemUrl"==d.action)switch(d.params.method){case "notif":c.notf=!0;break;case "dwnlApi":c.dwld=!0}else if("runScript"==d.action&&!d.params.bkgrnd||"sendInput"==d.action&&_kd(d.params,"intoPage")||_Or(d.action,"copyElemUrl",
"openElemUrl","saveElemUrl"))c.hst=!0;b=JSON.stringify([a,b]);/"type":"closedTabs"|"action":"(undoClose|reopen)"/.test(b)&&(c.ses=!0);/"type":"bmFolder"|"action":"(openBookmarks|bookmarkTabs)"/.test(b)&&(c.bkm=!0);_8j(a,d=>{d&&(c.bg=!0)});return Object.keys(c)}function _uj(a,b,c,d,e){$("body > tabs")[0].insertBefore($(`<tab pnlId="${b}" ${d}>${c}</tab>`)[0],$(`body > tabs > tab[pnlId='${a}']`)[0]);_Sk[b]={func:e}}
let _Jf=()=>a=>{let b=[],c=new _Wa(()=>a(b.sort()));for(let [d,e]of _Te.entries())_Sf.runtime.sendMessage(e,"ping",c.onReady(f=>!_pd()&&"pong"==f&&b.push(d)))};function _Zh(a){let b="";for(let c in a)b+=`[iconUID=TBBtn${c}]::before {background-image: url(${_kd(a[c],"icon","img")})} \n`;$("style[tbBtnIcons]").html(b)}function _6o(a){return a+1-(4<a?4:0)}
let _ot=new _qy,_Cf=_qf(function*(a){if(!$(a).is("[active]")){a=$(a).attr("pnlId");let b=$(`body > content > panel[pnlId='${a}']`)[0];if(!b){let [,c,d]=a.match(/^(.+?)(?::(\d+))?$/);b=$("<panel>").attr(c,"").attr("pnlId",a).css("pointer-events","none").appendTo("body > content")[0];let e=_Sk[c];e.templ&&$(b).append(_Ze(e.templ));e.func&&(yield e.func(b,d));setTimeout(_ug(function*(){yield f=>_Oa(f);yield _Fy(250);yield _2f(!0);_ot.send("",!0);$(b).css("pointer-events","")}))}$("body > tabs tab, body > content > panel").attr("active",
null).filter(`[pnlId='${a}']`).attr("active","");location.hash=a;return b}}),_ja=_qf(function*(a,b){document.body.insertAdjacentHTML("beforeend",`<import src="${a}"></import>`);yield _2f(b)});function _er(a){_gs()(b=>{_Xk("clear",b)(()=>{a(b)})})}function _9(a){return"actions"+(a?":"+a:"")}
var _5=_qf(function*(a,b,c=[],d=!1,[e,f]){if(yield _Ih(_Og(a),"permMsgs/impSttgs",!0))yield h=>_or(a,h),yield h=>_Ba._xi(h),_7p(c)&&(e=f?`<b>${e}</b> out of ${e+f} actions were successfully imported. <hr b=4> <b>${f}</b> actions were not imported for being identical <br> to existing actions.`:"Settings imported successfully.",d||f?_2(e,{type:"success"}):_Rs(e,1200)),_ha()(),$("body > content > panel").remove(),$("body > tabs > tab").attr("active",null),yield _Kw(_9(b)),c.forEach(h=>$(`trigAct[actionId='${h}']`).addClass("selected")),
_Ck($("trigActList")[0])});const _hy=_2g({trigActList:[],customEntities:{},toolbarBtns:{},sections:[]});
let _Mi=_ug(function*(a,b=!0,c=!1,d=!1,e=!1,f=!0){let h=a.trigActList.length;const l=yield g=>_sd(_hy,g,chrome);_jd(l,a,b,f);b=a.trigActList.length;c=c?Object.keys(a.trigActList):[];f=_kd(a.trigActList[Symbol.iterator]().next().value,1,"sctnId");a=_ur(l,a,d);yield _dy(yield _rs())._5(a,f,c,e,[b,h-b])}),_fe=_ug(function*(a,b,c=!1){try{var d=JSON.parse(a)}catch(e){_2("The file specified is not a valid AutoControl settings file.",{type:"error"});return}b||(b=(yield _gg())?"replace":yield _Wg(_Ze("askAddReplSettgs"),
{width:"initial"}));"replace"==b?yield _Ty(d):"add"==b&&(a=_my({}.add(_hy,d)),_Mi(a,!0,!1,!1,c))});var _Na=_ug(function*(a){let [b,c]=yield _Pw(_c(a,"text"));200!=c.status?_2(`Error while opening the file. <hr b=2> "${a}" <hr b=2> ${_jg(c.status,c)}`,{type:"error"}):_fe(b,"add",!0)});
