'use strict';var _Vt=(t=>null==t?null:{filePath:t})(_nt().file);let _4a=!0;
if(_Vt){let t=function(a,b,c,e){function l(...k){return new Proxy(()=>{},{get(f,g){f=[...k,g];var h=f.join(".");h=h in e?e[h]:b;if("function"===typeof h)return h(_kd(a,...f));if(h)return l(...k,g);g=_kd(a,...f);1<f.length&&"function"==typeof g&&(g=g.bind(_kd(a,...f.slice(0,-1))));return g},set(f,g,h){[...k]},apply(f,g,h){}})}return l()},m={},u={},p,q,n,y=_qf(function*(){u=(yield _Mt("customEntities"))||{}}),w=_qf(function*(a){m=a;yield y();n&&_4a&&n.toggleClass("noContent",_7p(m))}),z=_qf(function*(a){let [b,
c]=yield _Pw(_c(a,"text","GET",void 0,{"Cache-Control":"no-cache, no-store, max-age=0"}));return 200==c.status?{content:b}:{error:_jg(c.status,c)}}),A=_qf(function*(a){a=yield _Ba._tj(a,"text");a.error&&(a.error=yield _Ba._ky(_yk,+a.error));return a});_Vt.filePath&&(p=_qf(function*(){p=null;let a=_Hy(_Vt.filePath)?yield A(_Vt.filePath):yield z(_Vt.filePath);if(a.error)q=a.error;else if(_Vt.fileEncode=a.charEnc,a.content)try{yield w(JSON.parse(a.content))}catch(b){q="The format of the specified file is invalid."}}));
let B=a=>b=>{chrome.storage.local.set({["__dummy__"]:a},()=>{chrome.storage.local.get("__dummy__",c=>{chrome.storage.local.remove("__dummy__");b(c.__dummy__)})})},C=_F(400,()=>{n.addClass("unsaved").toggleClass("noContent",_7p(m));_4u()()});_4o=function(a){return t(a,!0,"CHROME",{tabs:null,windows:null,"runtime.id":null,"runtime.getManifest":null,"runtime.getURL":null,"runtime.lastError":()=>null,"extension.getViews":null,"extension.isAllowedFileSchemeAccess":null,"extension.isAllowedIncognitoAccess":null,
bookmarks:null,"storage.sync.QUOTA_BYTES":null,"storage.sync.getBytesInUse":null,"storage.local.get":()=>(b,c)=>{let e=()=>c(_wf({}.add(b,b?m.sc().keep(Object.keys(b)):m)));p?p()(e):setTimeout(e,0)},"storage.local.set":()=>(b,c)=>{let e=()=>{B(b)(l=>{m.add(l);n&&_4a&&C();c&&c()})};p?p()(e):e()},"permissions.getAll":()=>b=>setTimeout(()=>b({permissions:["bookmarks","sessions","background","notifications","downloads"],origins:["<all_urls>"]}),0),"runtime.sendMessage":()=>(b,c,e)=>{e&&("ping"==c?_sd({toolbarBtns:{}},
l=>{(_Te.indexOf(b)+"").in(Object.keys(l.toolbarBtns))?e("pong"):e()}):e())},"extension.getBackgroundPage":b=>()=>t(b(),!1,"BP",{"":"",_Jo:()=>u,_il:()=>({}),_Rh:()=>!1,_8i:!0,_xi:!0,_Ri:!0,_Od:!0,_Tj:!0,_rg:!0,_Yy:!0,_4w:!0,_xh:!0,_Ss:!0," ":""})})};let x=_qf(function*(a,b){_4a=!1;const c=yield f=>_sd({trigActList:[],toolbarBtns:{},sections:[]},f);let e={},l=[];"new"==b&&(b=_8y(),c.sections.push({id:b,name:"Imported actions"}),e[b]=!0);for(let f of Object.keys(c.trigActList)){var k=c.trigActList[f];
if(~a.indexOf(f)){void 0===b?e[k.sctnId]=!0:k.sctnId=b;for(let [g,h]of _2t(k.triggers))"eventId"==g&&(k=_T(h),k.type==_Wd&&_Uj(k.num)&&l.push(k.num-_yu))}else delete c.trigActList[f]}yield f=>_or({trigActList:c.trigActList,sections:c.sections.filter(g=>e[g.id]),toolbarBtns:c.toolbarBtns.keep(l)},f);yield _Ud();m.del("mouseGest","advOpts","userVars","joysticksOrder","previewMakerParams","scrtEdtr");_ir(m);_4a=!0});_Vt.afterLoad=_qf(function*(){function a(){let d=q||!_Vt.filePath?"New file":_Vt.filePath.replace(/^.*[\/\\]/,
"");document.title=d+" - Settings File Editor";$(window.frameElement).triggerEvt("titleChange")}let b=!1,c=()=>_Hy(_Vt.filePath)?_Vt.filePath.replace(/[^\\]+\.[^\\]+$/,""):"";const e=_qf(function*(d,r=m){if(!_Vt.filePath||q||d){d=yield _Js(_7p(r)?c():!_Vt.filePath||_Hy(_Vt.filePath)?_Vt.filePath:decodeURIComponent(_Bd(_Vt.filePath)),_ny,!0,_ia);if(!d)return!1;history.replaceState(null,"",location.pathname+"?file="+encodeURIComponent(d)+location.hash);_Vt.filePath=d;q=null;n.find("> [type=text]").val(d);
a()}let v;_Hy(_Vt.filePath)?(r=yield _Ba._7d(_Vt.filePath,_Bt(JSON.stringify(r),"UTF-8",!1)))&&(v=`Error while saving to the file. <hr b=2> "${_Vt.filePath}" <hr b=2> ${yield _Ba._ky(_yk,+r)}`):v='Changes cannot be saved to an internet address. <hr b> Click on "Save as" in order to save to a local file.';if(v)return _dy(!b&&window.frameElement?window.parent:window)._2(v,{type:"error"}),!1;n.removeClass("unsaved");return!0});let l=_Vt.safeToClose=d=>{n.is(".unsaved")?_Dg("","Unsaved changes will be lost if you continue. <hr b=2> Discard changes?")(d):
d(!0)},k,f=d=>{k=!0;location.replace(d)};$(window).on("beforeunload",d=>{if(!k&&n.is(".unsaved"))return"Discard changes?"});window.frameElement&&$(window).captureTgtEvt("mousedown",()=>$(window.frameElement).triggerEvt("mousedown",!0));p&&(yield p());a();yield d=>_gj("file92.css",d);n=$(`\n <fileEditBar helpCtx=sttgFilEdt>\n <img src="/AutoCtrl/logo32.png" width=26>\n <h h=welcm sides=br></h>\n <l>Settings file:</l>\n ${_ba("",q?"":_Vt.filePath,"No file path specified","readonly")}\n <!--btn act=new>New file</btn><h h=new></h-->\n <btn act=open>Open</btn><h h=opn sides=brl></h>\n <btn act=save>Save</btn><h h=sav sides=brl></h>\n <btn act=savAs>Save as</btn><h h=savAs sides=brl></h>\n <btn act=dscrd>Discard</btn><h h=disrd sides=brl></h>\n <btn act=impAll>Import all</btn><h h=imAll sides=brl bublCls=sharpCorner></h>\n </fileEditBar>\n `).on("click",
"btn",_ug(function*(d){d=$(this).attr("act");if(!d.in("new","open","dscrd")||(yield l))switch(d){case "new":(yield e(!0,{}))&&f(location.pathname+location.search);break;case "open":(d=yield _Js(c(),_ny))&&f(location.pathname+"?file="+encodeURIComponent(d));break;case "savAs":case "save":yield e("savAs"==d);break;case "dscrd":f("?file="+encodeURIComponent(_Vt.filePath));break;case "impAll":(yield _Dg("","This will add the entire content of this settings file <br> to your AutoControl settings. <hr b=2> Continue?"))&&
_Mi(yield r=>_sd(_hy,r))}})).appendTo(document.body);$(document.body).addClass("SFE_mode");let g=!0;var h=!0;if(null!=_nt().storInit){let [d,r]=window.frameElement.storInit;yield w(d);yield x(r);g=yield e(!0);h=`The actions have been successfully saved to: <hr b=2> "${_Vt.filePath}" <hr b=2> Do you want to review the file.`;h=g&&(yield _dy(window.parent)._Dg("",h,{icon:"success"}))}else _Vt.filePath||(yield w({}));$("body > tabs").append("<perms><tit>Permissions <h h=prmLst></h></tit><cont></cont></perms>");
$(window.frameElement).triggerEvt({contentReady:h});q&&setTimeout(()=>_2(`Error while opening the file. <hr b=2> "${_Vt.filePath}" <hr b=2> ${q}`,{type:"error"}),300);_0o("SFE_welcmShown",!0)||_eg(_ot.wait(),_Fy(50))(()=>$("[h=welcm]",n).triggerEvt({mousedown:!0}));b=!0;return g});let D=_qf(function*(a,b){const [c,e]=[_wf(m),_wf(u)];yield x(a,b);a=yield l=>_sd(_hy,l);[m,u]=[c,e];return a});var _Hr=_ug(function*(a,b){a=a.get().map(c=>$(c).attr("actionId"));a=yield D(a,b);_Mi(a,"new"!=b,!0,!0,!1,!1)})};
