'use strict';function _Yr(a){if(!a||"string"!=typeof a&&!a.templ)return a;let b=_rd(a.templ?a.templ:a).nodes[0].value;for(let c of b)_m(c);a={templ:b,regex:a.regex,flags:a.flags,ignoreCase:a.ignoreCase};1==a.templ.length&&"string"==typeof a.templ[0]&&(a=_Up(a,a.templ[0]));return a}function _Up(a,b){if(a.regex)try{return new RegExp(b,a.flags||(a.ignoreCase?"i":""))}catch(c){return/.^/}return a.ignoreCase?b.toUpperCase():b}
function _m(a){if(a&&a.expr)for(let b of a.expr)if(b.args)for(a=0;a<b.args.length;++a)_m(b.args[a]),b.args[a]=_Yr(b.args[a])}function _n(a,b=null){if(!a||!a.templ)return a;let c="";for(let d of a.templ)c+=d.expr?_wa(d,b):d;return _Up(a,c)}function _Pt(a,b=null){if(!a||!a.templ)return[a];let c=[""];for(let d of a.templ)if(d.expr){a=[];let e=_3g(_wa(d,b));for(let f of c)for(let g of e)a.push(f+g);c=a}else for(a=0;a<c.length;++a)c[a]+=d;return c}
function _wa(a,b){let c=_St(a.expr[0],b);for(let e=1;null!=c&&e<a.expr.length;++e){let f=a.expr[e];var d=_Lk.hasOwnProperty(f.name)?function(...g){return _0p(this)?this.map(h=>_Lk[f.name].apply(h.toString?h.toString():"",g)):_Lk[f.name].apply(this.toString?this.toString():"",g)}:c[f.name];c="function"==typeof d?d.apply(c,(f.args||[]).map(g=>g.expr?_wa(g,b):_n(g))):d}return void 0===c&&1==a.expr.length?`<${a.expr[0].name}>`:null==c?"(empty)":c}
const _Lk={match(a){return(this.match(a)||[""])[0]},matches(a){return this.match(a)||[]},replace(a,b){return this.replace(a instanceof RegExp?a.global?a:RegExp(a.source,"g"+a.flags):RegExp(_qr(""+a),"g"),b)},escape(){return encodeURIComponent(this).replace(/%20/g,"+")},unescape(){return unescape(this)},lines(){return this.trim().split(/\s*\n\s*/)},words(){return this.trim().split(/\s+/)},url(){return new Proxy(new String(_Yh(this)),{get:_7o})}};
let _7i,_yr,_Ho={},_Fo={},_Rp=_qf(function*(a){if(null==_Ho[a]){let b=yield _ky(_uo,_cs[a]);_Ho[a]="string"==typeof b?b:""}return _Ho[a]}),_wg=_qf(function*(a){null==_Fo[a]&&(_Fo[a]=yield _ky(_Ai,a));return _Fo[a]});
var _9i=_qf(function*(a){if(!a)return a;const b=/<(\w+)>/g;let c={};a=_3g(a);for(let d=0;d<a.length;++d){let e=a[d].match(b);if(e){for(let f of e)f=f.slice(1,-1).toLowerCase(),c.hasOwnProperty(f)||(c[f]=_cs[f]?yield _Rp(f):yield _wg(f));a[d]=a[d].replace(b,(f,g)=>c[g.toLowerCase()])}}return 1==a.length?a[0]:a});
{let a={};var _St=function(b,c){switch(b.name.toLowerCase()){case "clipboard":if(c=_kd(b.args,0))return _hf[c]||"";_A()&&_hj.addFunc(_ok);return _Wj.content;case "omnibox":return null==_7i&&_fy[_Ui]&&_hj.addFunc(_Uw(function*(){null==_7i&&(_7i=yield _ky(_tu,_fy[_Ui]))})),_7i||"";case "selection":return null==_yr&&_hj.addFunc(_Uw(function*(){null==_yr&&(_yr=(yield _io(1E3*(+_kd(b.args,0)||.5))).content||"")})),_yr||"";case "date":return _Eg(new Date,"string"==typeof _kd(b.args,0)?b.args[0]:"Y-M-D");
case "var":return new Proxy(a,{get(d,e){if("string"!=typeof e||_Or(e,"toString","valueOf"))return d[e];if(d.hasOwnProperty(e)){let f=d[e];delete d[e];return void 0===f?"":f}_hj.addFunc(_Uw(function*(){d[e]=yield _Br("",e)}));return" "}});case "dir":return new Proxy(_Ho,{get(d,e){if("string"!=typeof e||_Or(e,"toString","valueOf"))return d[e];e=e.toLowerCase();if(!_cs[e])return"";if(d.hasOwnProperty(e))return d[e];_hj.addFunc(_Rp(e));return" "}});case "env":return new Proxy(_Fo,{get(d,e){if("string"!=
typeof e||_Or(e,"toString","valueOf")||d.hasOwnProperty(e))return d[e];_hj.addFunc(_wg(e));return" "}});default:return _ci(c,b.name)}}}function _Mu(){if(null!=_gt)return _gt;_hj.addFunc(_Uw(function*(){_gt=(yield _Iu(null,_xu(_Dt).usePrevMousePos))||0}));return 0}function _Ut(a){return a.active&&a.highlighted?a.window.tabs.some(b=>!b.active&&b.highlighted):a.highlighted}let _gy,_Is;
function _pt(){if(_gy)return _gy;_Is||(_Is=!0,_hj.addFunc(_Uw(function*(){for(var a={usePrvMsPos:!!_xu(_Dt).usePrevMousePos};;){a=(yield _ky(_0e,a))||{};const b=_gt=_oj[a.hWnd];let c=[];if("index"in a)c=yield _Ge({windowId:b,index:a.index});else if("title"in a&&((c=yield _8w(b,a.title))||(c=[yield d=>_Vy(b,d)]),1!=c.length)){a={x:a.x,y:a.y,getIdx:!0};continue}a.group&&c[0]&&c[0].groupId&&(c=yield _Ge({windowId:b,groupId:c[0].groupId}));_gy=c.map(d=>_at(d));break}_Is=!1})));return[]}
let _8w=_qf(function*(a,b){if(!b)return[];const c=500==b.length;for(;;){var d=b.replace(/\*|\?/g,"\\$&");c&&(d+="*");if((d=yield _Ge({windowId:a,title:d}))&&0==d.length){let e=b.lastIndexOf(" - ");if(0<e){b=b.slice(0,e);continue}}return d}}),_6=_qf(function*(a,b){if(!b)return[];for(let d=0;;){d=b.indexOf(" - ",d+1);-1==d&&(d=void 0);var c=b.slice(0,d).replace(/\*|\?/g,"\\$&");d&&(c+="*");c=yield _Ge({windowId:a,title:c});if(!d||!c||1>=c.length)return c}});
function _ws(a){return 0<=_jf.indexOf(a)}let _g={};function _et(a){if(null!=_g[a])return _g[a];_g[a]=null;_g.pending||(_g.pending=!0,_hj.addFunc(_Uw(function*(){yield _Fy();delete _g.pending;_g=yield _yt(Object.keys(_g).map(b=>+b))})));return!1}
function _ci(a,b){if(!a)return"";switch(b){case "url":return new Proxy(new String(_uu(a)),{get:_7o});case "domain":case "mainDomain":case "dirPath":case "path":return _7o(_uu(a),b);case "muted":return a.mutedInfo.muted;case "monitorId":return _1(a.window);case "window":return new Proxy(a.window,{get(c,d){switch(d){case "underMouse":return c.id==_Mu();case "state":return _ws(c.id)?"hidden":c.state;case "focused":return _gp(c);case "alwaysOnTop":return _et(c.id)}return c[d]}});case "status":return a.discarded?
"discarded":a.status;case "index":return a.index+1;case "selected":case "highlighted":return _Ut(a);case "openerTabId":return a.openerTabId||_7j(a.id);case "used":return 0<=_Yk.indexOf(a.id);case "hovered":return 0<=_pt().indexOf(a.id);case "contType":return"";default:return a[b]}}function _7j(a){if(a=_Ee[a])return a in _ts?a:_7j(a)}
function _7o(a,b){switch(b){case "protocol":return(new URL(a)).protocol;case "user":return(new URL(a)).username;case "domain":return(new URL(a)).hostname;case "mainDomain":return _3t((new URL(a)).hostname);case "port":return(new URL(a)).port;case "path":return(new URL(a)).pathname;case "dirPath":return(new URL(a)).pathname.replace(/[^\/]+$/,"");case "query":return new Proxy(new String((new URL(a)).search),{get:_zr});case "fragment":return(new URL(a)).hash}b=a[b];"function"==typeof b&&(b=b.bind(a));
return b}function _zr(a,b){let c=a[b];"function"==typeof c?c=c.bind(a):void 0===c&&"string"==typeof b&&(a=(new URLSearchParams(a.slice(1))).getAll(b),c=1>=a.length?a[0]:a);return c}function _3t(a){let b=a.match(/[^.]+(?:\.(?:gov|com|org|edu|net|co|mil|eu|ac|info|biz|leg|int|nom|name|gob|web))?\.(?!\d+)[^.]+$/i);return b?b[0]:a}function _Nu(a,b){let c=!1,d=Object.keys(_ts)[0],e=new Proxy(_ts[d]||{},{get(f,g){g in f&&(!b||"url"!=g)&&(c=!0);return f[g]}});_se(0,()=>_n(_Yr(a),e))(_cy);return c}
let _rd=(()=>{let a={ident:b=>({value:b}),num:b=>({value:+b}),str:b=>({value:_Ky(b.slice(1,-1),"nrt'\"\\")}),regexBody:b=>({value:_Ky(b.slice(1,-1),"/")}),regexFlags:b=>({value:b}),regex:()=>({value:{regex:!0},addChild(b){this.value[this.value.templ?"flags":"templ"]=b.value}}),argList:()=>({value:[],addChild(b){this.value.push(b.value)}}),exprComp:()=>({value:{},addChild(b){this.value[this.value.name?"args":"name"]=b.value}}),expr:()=>({value:{expr:[]},addChild(b){this.value.expr.push(b.value)}}),
text:b=>({value:b}),templateStr:()=>({value:[],addChild(b){"string"==typeof this.value[this.value.length-1]&&"string"==typeof b.value?this.value[this.value.length-1]+=b.value:this.value.push(b.value)}})};a.exprComp2=a.exprComp;a.text2=a.text;return _Iw({blank:/\s*/,ident:/[a-z_]\w*/i,num:/[+-]?\d+(\.\d*)?/,str:/(["'])((?!\1)[^\\]|\\.)*\1/,regexBody:/\/([^\\\/]|\\.)*\//,regexFlags:/[a-z]{1,10}/i,regex:" regexBody regexFlags? ",value:"str|regex|num|expr",argList:'"(" (value ("," value)*)? ")"',exprComp:"ident argList?",
exprComp2:'"[" value "]" argList?',expr:' exprComp ( ("." exprComp) | exprComp2 )* ',text:/[^<]+/,text2:/<[^<]*/,templateStr:' (text | ( "<" . expr . ">" ) | text2)* '},"templateStr",a)})();
