'use strict';let _Zt=_ug(function*(b,f,a,d){if(!a.url&&!a.bookmarkId)return f(b);let c=[],e=[],g=!1;if(a.bookmarkId&&_Sf.bookmarks){var h=yield m=>_Sf.bookmarks.getSubTree(""+a.bookmarkId,m);if(!_pd()&&h.length)if(h[0].url)e=[h[0].url];else{g=!0;for(var k of h[0].children)k.url&&e.push(k.url)}}(h=a.refTab)&&"number"!=typeof h&&(h=(yield _xd(d,_zk,h))[0][0]);h=_ts[h]||_ts[_7h];h||(a=a.sc().add({tabPos:"newWin"}),h={});let n=h.windowId;b=_Ga(b);b=a.tabPos&&!a.usesTabs?[]:b;let q=(h.index||0)+("after"==
a.tabPos?1:0);b.length||(b=[void 0]);for(h=0;h<b.length;){k=h;a.bookmarkId||(e=_0p(a.url)?a.url:yield _xd(d,_Pt,_Yr(a.url||"chrome://newtab"),_ts[b[h]]));for(let m of e)if(m=m.trim().match(/^.*/)[0].trim(),_9u(m)){_wu=Date.now();if("newWin"==a.tabPos)if(0==h||"popup"==a.winType){var l=yield p=>_Wh({url:m,focused:!1,incognito:a.incognito,type:a.winType},p);!_pd()&&l&&(n=l.id,c.push(l.tabs[0].id))}else(l=yield p=>_pu({url:m,active:!1,windowId:n},p))&&c.push(l.id);else if(a.tabPos)(l=yield p=>_pu({url:m,
active:!1,windowId:n,index:q++},p))&&c.push(l.id);else if(l=b[h],0<l)m.startsWith("javascript:")?_9j(l,{code:m.slice(11)})():_Sf.tabs.update(l,{url:m}),c.push(l);else if(a.newTabs){let p=_kd(_ts[b[b.length-1]||_7h],"windowId");(l=yield r=>_pu({url:m,active:!1,windowId:p},r))&&c.push(l.id)}++h}if(g||1<e.length&&1<b.length)break;h==k&&++h}f([c])});
function _6t(b){return[{sequence:[{action:"loadUrls",params:{url:"blank"==b.page?"about:blank":"chrome://newtab",tabPos:"after",refTab:"lastTab"}},{action:"activateTabs"}]}]}function _Ow(b,f,a){let d=new _Wa;for(let c of _Ga(b))0<c&&_Sf.tabs.reload(c,{bypassCache:!!a.force},d.onReady());d.setCallback(()=>f(b))}function _Sy(b){return _ts[b].active&&_gp(_ts[b].window)}
function _ap(b,f,a,d,c){let e=new _Wa;for(let g of _Ga(d))if(0<g)if(_Sf.tabs[b])_Sf.tabs[b](g,e.onReady());else _Sy(g)?_Ya(_9p,a,e.onReady()):_9j(g,{code:f})(e.onReady());e.setCallback(()=>c(d))}function _vo(b,f){_ap("goBack","history.back()",[_zg,_No,_No|_Lw,_zg|_Lw],b,f)}function _7w(b,f){_ap("goForward","history.forward()",[_zg,_gu,_gu|_Lw,_zg|_Lw],b,f)}
function _Hw(b,f){let a=new _Wa;for(let d of _Ga(b)){if(!(0<d))continue;let c=_ts[d],e=_di(c.url);e!=c.url&&_Sf.tabs.update(d,{url:e},a.onReady())}a.setCallback(()=>f(b))}
function _2y(b,f,a={}){let d=new _Wa;var c={};for(let e of _Ga(b))_ts[e]&&_ng(c,_ts[e].windowId,[]).push(e);b=Object.keys(_pj);for(let [e,g]of c)c=_pj[e],c.tabs.length==g.length?"devtools"!=c.type&&(("lastWin"==a.keepWin?1==b.length:a.keepWin)&&"normal"==c.type?(_pu({url:"about:blank",active:!1,windowId:+e},d.onReady()),_Sf.tabs.remove(g,d.onReady())):(_Sf.windows.remove(+e,d.onReady()),b.remove(e))):((c=_6i(e,g,a.switchTo))&&_Sf.tabs.update(c,{active:!0}),_Sf.tabs.remove(g,d.onReady()));d.setCallback(_ug(function*(...e){f([e.filter(g=>
g).map(g=>g.id)])}),1E3)}
function _6i(b,f,a){const [d]=f.filter(c=>_ts[c].active);if(d&&a){b=_pj[b].tabs.map(e=>e.id);const c=_0w(b,f);if(1<c.length){const e=b.indexOf(d);switch(a){case "prevUsedTab":return _ls(c,_Yk,!0).slice(-1)[0];case "openerTab":return _Cr(_Ng(d),c)[0];case "leftTab":return _0w(b.slice(0,e),f).slice(-1)[0]||_0w(b.slice(e+1),f)[0];case "rightTab":return _0w(b.slice(e+1),f)[0]||_0w(b.slice(0,e),f).slice(-1)[0];case "firstTab":return c[0];case "lastTab":return c[c.length-1]}}}}
function _Ng(b){let f=[];for(;b=_ci(_ts[b],"openerTabId");)f.push(b);return f}function _bj(b){return[{sequence:[{action:"closeTabs",params:b}],targets:"currentTab"}]}
function*_zs(b,f,a,d){const c={[_8f]:"href",[_Vs]:"hostname",[_rk]:"pathname"};let e=h=>!a||a.regex.test((new URL(h.url))[c[a.part]])==!a.negate,g=_kd(_ts,_7h,"windowId");for(let h of b)h.window?"tab"==f?yield*_zs(h.window.tabs,f,a,d):h.window.tabs.some(e)&&(yield h.window.sessionId):f&&"tab"!=f||(b=h.tab||h,e(b)&&(!d||g&&g==_Ad[b.sessionId])&&(yield b.sessionId))}
let _Yw=_ug(function*(b,f,a,d){let c;if(b=(a.urlTest||{}).value)d=yield _xd(d,_n,_Yr(b),_ts[_7h]),c=a.urlTest.sc().add({part:_Vs,value:d,regex:_i(d,a.urlTest.type)});d=0;b=[];let e=a.maxObjs||1;if(_Sf.sessions){var g=yield h=>_Sf.sessions.getRecentlyClosed(a.objType||c||a.currWinTabs?{}:{maxResults:Math.min(e,_Sf.sessions.MAX_SESSION_RESULTS)},h);for(let h of _zs(g,a.objType,c,a.currWinTabs))if(g=yield k=>_Sf.sessions.restore(h,k),!_pd()&&g&&b.push(...g.tab?[g.tab.id]:g.window.tabs.map(k=>k.id)),
++d>=e)break}f([b])});function _3u(b,f){let a=[],d=new _Wa;for(let c of _Ga(b))0<c&&_Sf.tabs.duplicate(c,d.onReady(e=>a.push(e.id)));d.setCallback(()=>f(a))}function _Ys(b,f=_cy,a={}){let d=new _Wa;for(let c of _Ga(b)){let e=_ts[c];0<c&&e&&(a.peek&&(_Uu[c]=1),e.active?2==_Uu[c]&&_qp(c,e.windowId!=_Ui):_Sf.tabs.update(c,{active:!0},d.onReady()))}d.setCallback(()=>f(b))}
function _zj(b,f){let a=new _Wa;for(let d of _Ga(b))0<d&&_Sf.tabs.discard&&_Sf.tabs.discard(d,a.onReady());a.setCallback(()=>f(b))}function _gw(b,f){_Zt([],f,{url:_Ga(b).filter(a=>0<a).map(a=>_uu(_ts[a])),tabPos:"newWin",incognito:!0})}function _Lg(b,f,a){let d=new _Wa;for(let c of _Ga(b))0<c&&_Sf.tabs.update(c,{muted:a.mode==_Fa?!_ts[c].mutedInfo.muted:!!a.mode},d.onReady());d.setCallback(()=>f(b))}
function _Va(b,f,a){let d=new _Wa;for(let c of _Ga(b))0<c&&_Sf.tabs.update(c,{[a.propName]:a.mode==_Fa?!_ts[c][a.propName]:!!a.mode},d.onReady());d.setCallback(()=>f(b))}function _Pu(b,f,a){_Va(b,f,{}.add(a,{propName:"pinned"}))}
function _1o(b,f,a){let d={true:[],false:[]};if(a.inclActTab){var c=_Ga(b);for(var e of _Fe(c)){let h=_pj[e].activeTab.id;0>c.indexOf(h)&&b.push([h])}}for(var g of _Ga(b))c=_ts[g],0>g||!c||(e=a.mode==_Fa?!_Ut(c):!!a.mode,d[e][c.active?"push":"unshift"](g),e&&c.active&&_Sf.tabs.update(g,{highlighted:!1}));a=new _Wa;g={};for(let h of d[!0])c=_ts[h].windowId,c in g||(g[c]=_pj[c].tabs.some(k=>_Ut(k))),_Sf.tabs.update(h,{highlighted:!0,active:!g[c]},a.onReady()),g[c]=!0;for(let h of d[!1])_Sf.tabs.update(h,
{highlighted:!1},a.onReady());a.setCallback(()=>f(b))}function _R(b,f,a){let d={},c=[];b[0]&&!_0p(b[0])&&(b=[b]);for(let e of b){b=[];for(let g of e)f&&d[g]||a&&!a(g)||(d[g]=!0,b.push(g));b.length&&c.push(b)}return c}
let _ey=_ug(function*(b,f,a,d){b=_R(b,!0,e=>"normal"==_ts[e].window.type);if("newWin"==a.pos)for(let e of b){a=_ts[e[0]].window.tabs;if(a.length==e.length&&0==_0w(e,a.map(h=>h.id)).length)continue;a=e.filter(h=>_ts[h].active)[0];let g=yield h=>_kp(e[0],h);1<e.length&&(yield h=>_Sf.tabs.move(e.slice(1),{windowId:g.id,index:-1},h),a&&_Sf.tabs.update(a,{active:!0}))}else{let e=_Ga(b);var c=!0;a.refTab&&(c=(yield _xd(d,_zk,a.refTab))[0][0]||_7h,c=!(yield _nd(e,c,a.pos)))}f(c?[]:b)}),_nd=_qf(function*(b,
f,a){let d=_ts[f];if(d&&"normal"==d.window.type){b="after"==a?b:b.slice().reverse();for(let c of b){if(c==f)continue;b=yield g=>_Sf.tabs.get(c,g);if(!b)continue;let e=d.index+("after"==a?1:0);b.windowId==d.windowId&&b.index<e&&--e;d=(yield g=>_Sf.tabs.move(c,{windowId:d.windowId,index:e},g))||d}return!0}});
function _kp(b,f){let a=_ts[b].window;if(1<a.tabs.length){let d=_cy,c={};"normal"==a.state&&(c=a.sc().keep("left","top","width","height"),d=g=>_Sf.windows.update(g.id,c));let e=_gp(a)||a.state.in("maximized","fullscreen");_Sf.windows.create({tabId:b,focused:e,state:a.state,incognito:a.incognito}.add(c),g=>{d(g);f(g)})}else f(a)}function _wr(b,f){let a=new _Wa;for(let d of _Ga(b))_kp(d,a.onReady());a.setCallback(()=>f(b))}
let _Ep=_ug(function*(b,f,a,d){function c(h){let k={},n;for(let q of h)h=_ts[q].windowId,k[h]=(k[h]|0)+1,k[h]<=k[n]||(n=h);return n}var e=_R(b,!0,h=>"normal"==_ts[h].window.type);let g=_Ga(e);if("no"==a.target)_7p(g)||(yield h=>_Sf.tabs.ungroup(g,h));else if("new"==a.target)b=e,_7p(g)||(yield h=>_Sf.tabs.group({tabIds:g,createProperties:{windowId:c(g)}},h));else if(b=e,!_7p(g)&&(d=(yield _xd(d,_zk,a.refTab))[0][0],e=_kd(_ts[d],"groupId"),!a.noNewGrp||0<e))if(yield _nd(g,d,a.target)){let h=0<e?{tabIds:g,
groupId:e}:{tabIds:g.concat(d),createProperties:{windowId:c(g)}};yield k=>_Sf.tabs.group(h,k)}f(b)});
function _do(b,f){let a,d=[.2,.21,.22,.23,.24,.25,.26,.275,.29,.305,.32,.335,.35,.365,.38,.4,.42,.44,.46,.48,.5,.52,.55,.58,.61,.64,.67,.7,.74,.78,.82,.86,.9,.95,1,1.05,1.1,1.15,1.2,1.27,1.34,1.4,1.47,1.55,1.63,1.7,1.8,1.9,2,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3,3.15,3.3,3.45,3.6,3.8,4,4.2,4.4,4.6,4.8,5,5.25,5.5,5.75,6];for(let c of 0<f?d:d.reverse())if(0<(c-b)*f&&(a=c,0==(f-=f/Math.abs(f))))break;return a}
function _la(b,f,a=!1){_Sf.tabs.setZoomSettings(b,{scope:a?"per-tab":"per-origin"},()=>_pd()||_Sf.tabs.setZoom(b,f))}let _8={};
function _oa(b,f,a){for(let d of _Ga(b)){if(0>d)if(_ts[d]&&_ts[d].windowId==_Ui)d=null;else continue;_Sf.tabs.getZoom(d,c=>{c=_Pa(c,3);let e=0==a.type?0:"custom"==a.type?a.amount/100:2==Math.abs(a.type)?_b(c+a.type/2*a.amount/100,.1,8):_do(c,a.type*(a.steps||1));void 0!==e&&e!=c&&(a.perTab?(_Sf.tabs.onZoomChange.hasListeners()||_Sf.tabs.onZoomChange.addListener(g=>{500>Date.now()-_8[g.tabId]||"per-origin"!=g.zoomSettings.scope&&_Pa(g.oldZoomFactor,2)==_Pa(g.newZoomFactor,2)||(delete _It[g.tabId],
"per-tab"==g.zoomSettings.scope&&(_Sf.tabs.setZoomSettings(g.tabId,{scope:"per-origin"}),_Sf.tabs.setZoom(g.tabId,g.newZoomFactor)))}),_It[d]=e,_8[d]=Date.now()):delete _It[d],_la(d,e,a.perTab))})}f(b)}
function _Si(b,f,a){let d=_ng(_0k,a.listId,[]);for(let c of d)_ts[c]||("function"==typeof d.remove?d.remove(c):_Pf("badFavList",{list:d,listType:typeof d,listId:a.listId}));switch(a.oper){case "set":d=_0k[a.listId]=[];case "add":for(let c of _Ga(b))d.add(c);break;case "del":for(let c of _Ga(b))d.remove(c)}f(b)}function _we(b,f,a,d){_xd(d,_zk,a.tse,b)(f)};
