'use strict';let _if=_qf(function*(){for(let b=0;10>b;++b){var a=speechSynthesis.getVoices();if(!_7p(a))break;yield _Fy(5)}return a});function _4d(a,b,c){for(let d of b)a[d]&&a[d].addListener(c)}function _Qr(a,b,c){for(let d of b)a[d]&&a[d].removeListener(c)}
window.addEventListener("error",a=>{var b=a.composedPath&&a.composedPath().map(c=>c.nodeName);b={tgtElem:_kd(a,"target","nodeName"),path:b};a.error&&b.add({error:a.error,stack:a.error.stack,elemSrc:a.error.src});b.stack||b.add({msg:a.message,file:a.filename,line:a.lineno,col:a.colno});_Pf("error",b)},!0);function _e(){return(Math.round(_Ba._Ia/100)%parseInt("zzzzzz",36)).toString(36)}
const _pd=(a,b,c)=>_Sf.runtime.lastError,_qs=(a=!1)=>b=>{_Sf.windows.getAll({populate:a,windowTypes:_2k},c=>b(c.filter(d=>!_Ba._Bp[d.id])))},_Ge=(a={})=>b=>{_Sf.tabs.query(a,c=>b(c&&c.filter(d=>!_Ba._Bp[d.windowId])))},_Ur=(a,b=!1,c)=>_Sf.windows.get(a,{populate:b,windowTypes:_2k},c),_uu=a=>a&&(a.url||a.pendingUrl)||"about:blank";function _at(a){return a.id==_Sf.tabs.TAB_ID_NONE?-a.windowId:a.id}function _gp(a={}){return a.focused&&"minimized"!=a.state}
let _ht=a=>b=>{_Sf.tabs.create({url:a,active:!0},c=>{_Sf.tabs.onUpdated.addListener(function g(f,e){f==c.id&&"complete"==e.status&&(_Sf.tabs.onUpdated.removeListener(g),b(c))})})},_Qt=_qf(function*(a){let b=yield c=>_Sf.windows.getLastFocused(c);a.windowId!=b.id&&_Sf.tabs.move(a.id,{windowId:b.id,index:-1});return yield c=>_Sf.tabs.update(a.id,{active:!0},c)}),_oy=_qf(function*(a=""){let b=yield _Ge({url:_Sf.runtime.getURL(_ce)});b=b.filter(c=>!_yg(_uu(c)));return b[0]?yield _Qt(b[0]):yield _ht(_ce+
"#"+a)}),_yo=_qf(function*(){var a=yield _oy("none");a=_Sf.extension.getViews({tabId:a.id})[0];yield _dy(a)._Wp.wait();return a}),_rs=_qf(function*(){return window==_Ba||_Vt?window.frameElement&&!_dy(window.parent)._Vt?window.parent:yield _yo():window}),_Xr,_Mp=/^ /;_Sf.extension.isAllowedFileSchemeAccess(a=>{_Xr=a;_Mp=new RegExp(`^(chrome|edge|about:|data:|view-source:|https:\/\/chrome.google.com\/webstore\/${a?"":"|file:"})`,"i")});const _vf=a=>_Mp.test(a);
function _xs(a){return a.charCodeAt(0)}function _eu(a){return String.fromCharCode(a)}function _i(a,b,c=!0){return RegExp((b.in("equals","starts")?"^":"")+_qr(a)+(b.in("equals","ends")?"$":""),c?"i":"")}function _qr(a){return _Wt(a,"^$\\.*+?()[]{}|")}function _Yf(a){return a.split(":")}function _Tp(a){return!(!a||!_Yf(a)[1])}function _Np(a,b=null){if(!a)return{};const c=_Yf(a),d=1<c.length;d&&([b,a]=c);return _kd(d?_Ba._Jo:_Ba._tt,b,a)||{}}
function _3p(a,b){a=_Np(a,"action").value;a.gener&&(a=a.gener(b));return a}function _5g(a,b,c,d){a=_3g(a);let f=_Yf(a.shift());_O(["customEntities"].concat(f,a),b,c,d)}function*_ea(a,b=!1){const c=_Ba._Jo[a]||{};let d=Object.keys(c).filter(f=>c[f].name&&c[f].value);b&&d.sort((f,e)=>_ck(c[f].name,c[e].name));for(let f of d)yield a+":"+f}let _k={};var _8g=a=>b=>{var c=a.match(/^data:[^;]*;base64,(.+)$/);if(c)return b(c[1]);if(c=_k[a])return b(c);_c(a,"binary")(d=>b(_k[a]=btoa(d)))};
function _Pf(a,b={},c){if(_Ba._ki()&&a.in("error","NH-error","NH-except","userReload"))return c&&c();const d=navigator;var f=(d.userAgent.match(/\((.+?)\)/)||[,""])[1].split(/\s*;\s*/);const e=[..._Ba._Vw].map(([,g])=>100*g.dpiX/96);f={uri:location.pathname+location.search+location.hash,natHostVer:"2024.6.19.0",brwrLang:d.language,brwrVariant:_7p(_3d)?void 0:_3d,osExtra:f[1]||d.platform,scaleFctr:1==e.length&&100==e[0]?void 0:e};_Ba._Xs&&(f.connectTime=Date.now()-_Ba._Xs);_c(_5y+"appEvent","json",
"POST",_re({extName:"AutoCtrl",extVer:"2024.6.19",eventType:a,instID:_Ba._Dh,timeOffset:Math.floor((Date.now()-_Ba._Ia)/1E3),opSys:_1i?d.platform+" "+_1i:d.platform.match(/^win/i)?"Windows":d.platform,brwrName:_Ba._ik||_3d[0]||"",brwrVer:_Zo,ctxData:JSON.stringify(f),evtData:JSON.stringify(b),domain:location.hostname}))(c)}function _1y(a,b){null!=b&&_Sf.browserAction.setBadgeBackgroundColor({color:b});null!=a&&_Sf.browserAction.setBadgeText({text:a})}
function _ff(a,b=!1){const c=[94,14,77,49,13];let d=b?new Uint8Array(a.length):"";for(let f=a.length;0<=--f;){let e=a.length-f-1,g=(a.charCodeAt(f)-c[e%c.length]-e)%256;0>g&&(g+=256);b?d[e]=g:d+=String.fromCharCode(g)}return d}
let _ao=_qf(function*(a,b){const c="B64"==b,d="blob"==b,f=/\.dat$/.test(a);if(d&&f||c)b="binary";b=yield _c(a,b);f&&(b=_ff(b,d),/\.gz\./.test(a)&&(b=d?yield _Ue(new Blob([b]),"gzip"):yield _lu(b,"gzip")),!d||b instanceof Blob||(b=new Blob([b])));c?b=btoa(b):b instanceof Blob&&(b=new Blob([b],{type:"application/vnd.microsoft.portable-executable"}));return b});
function _Pp(a,b,c=document){"string"==typeof c&&(c=document.querySelector(c));a=c.querySelector("#"+a).innerHTML.trim();b={URLS:_xg,EXT:_Qk}.add(b);return a=a.replace(/\$\{([\w.#]+)\}/g,(d,f)=>"#"==f[0]?_Pp(f.substr(1),b,c):_kd(b,...f.split(".")))}let _dy=a=>a;
var _br=_ug(function*(a,b,c){let d=yield k=>_Sf.windows.getLastFocused(k),f=_6p(_8e(_Ba._Vw[_Ba._1(d)].workArea)),e=a.width||400,g=a.height||200,h=yield k=>_Sf.windows.create({width:e,height:g,left:f.x-e/2|0,top:f.y-g/2|0,url:"file14.html",focused:!0,type:"popup",state:"normal"},k);_Np("topmostWins","action").value([h.tabs[0].id],_cy,{mode:_Ns});_Sf.tabs.onUpdated.addListener(function r(m,p){if(m==h.tabs[0].id&&"complete"==p.status){_Sf.tabs.onUpdated.removeListener(r);let l=_Sf.extension.getViews({windowId:h.id})[0];
l.document.title=_Cw.AutoCtrl.name;l.document.body.insertAdjacentHTML("beforeend",`\n <content>\n <img src="${"AutoCtrl"}/logo48.png">\n <msg value={}>${b}</msg>\n </content>\n <actions>\n <button yes>${a.yes||"OK"}</button>\n ${!1===a.no?"":`<button no>${a.no||"Cancel"}</button>`}\n </actions>\n `);function q(){var n=_kd(l.document.body,"offsetHeight");n&&(n=Math.max(0,l.outerHeight-l.innerHeight)+n,_Sf.windows.update(h.id,{height:n,top:l.screenY-(n-l.outerHeight)/2|0}))}for(let n of l.document.images)n.onload=
q;setTimeout(q,150);q();l.onclick=function(n){n.target.closest("button")&&(this.dialogResult=n.target.hasAttribute("yes"),_Sf.windows.remove(h.id))};l.onunload=function(){c&&this.$&&c(_dy(this)._Me(this.$("msg[value]")[0]).add({answer:!!this.dialogResult}))};a.onloaded&&_dy(l)._Wp.wait()(()=>a.onloaded(l))}})}),_hw=_ug(function*(a,b){b||(b=yield _Mt("toolbarBtns",a));if(_kd(b,"icon","img")){var c=yield _7g(b.icon.img);let d=_Ld(c.width,c.height).getContext("2d");d.drawImage(c,0,0);c=d.getImageData(0,
0,c.width,c.height);c={data:[...c.data],width:c.width,height:c.height}}b=(_kd(b,"title")||"").replace(/<br>/g,"\n")+"\v"+Array(+a+2).join("\t");_Sf.runtime.sendMessage(_Te[a],{type:"btnProps",title:b,icon:c})});
{var _Ej=function(e,g){try{switch(g){case "UTF-16LE":return f(e,!1);case "UTF-16BE":return f(e,!0);case "UTF-8":case "US-ASCII":return c(e)}}catch(h){}return e},_Bt=function(e,g,h=!0){switch(g){case "UTF-16LE":return d(e,!1,h);case "UTF-16BE":return d(e,!0,h);default:try{return btoa(e),e}catch(k){}case "UTF-8":return b(e,h)}};const a=String.fromCharCode(65279),b=function(e,g){e=e.length&&65279!=e.charCodeAt(0)&&g?a+e:e;return unescape(encodeURIComponent(e))},c=function(e){e=decodeURIComponent(escape(e));
return 65279==e.charCodeAt(0)?e.substr(1):e},d=function(e,g=!1,h){e=e.length&&65279!=e.charCodeAt(0)&&h?a+e:e;h=8*+g;g=8*+!g;let k="";for(let m=0;m<e.length;++m){const p=e.charCodeAt(m);k+=String.fromCharCode(p>>h&255);k+=String.fromCharCode(p>>g&255)}return k},f=function(e,g=!1){const h=+g;g=+!g;let k="";for(let m=0;m<e.length;m+=2)k+=String.fromCharCode(e.charCodeAt(m+h)|e.charCodeAt(m+g)<<8);return 65279==k.charCodeAt(0)?k.substr(1):k}}
function _ak(...a){return 1==a.length?_wk(a[0]):_D(a[0],a[1])}function _yg(a){"string"==typeof a&&(a=new URL(a));a=(a.hash||"").slice(1);return a.startsWith("script=")?a.split("=")[1]:!1}function _8j(a,b){_Du({trigActList:null,mouseGest:{}},a,c=>{let d=[];for(let [,f]of c.trigActList)f.disabled||d.push(f.triggers);"other"==_kd(c.mouseGest,"triggers","preset")&&d.push(c.mouseGest.triggers);b(!!JSON.stringify(d).match(/"closed":true/))})}
let _Xk=_qf(function*(a,b){if(!b){b=yield d=>_sd({trigActList:[]},d);var c=0}for(let [d,f,e]of _2t(b.trigActList))if("preconds"==d&&f.chromeState&&(f.chromeState.inactive||f.chromeState.closed)){switch(a){case "set":e.author={};case "del":case "add":_ng(e,"author",_Ba._Dh,"del"==a?void 0:1,NaN);break;case "clear":e.author&&(e.author=void 0)}++c}c&&(yield d=>_or(b,d));return!!c});
function _Cs(a){if(a.author&&_Ba._Rh){let b=_kd(a,"preconds","chromeState");return b&&!a.author[_Ba._Dh]&&(b.inactive||b.closed)}return!1}function _nk(a,b,c,d){d=d||1024;b=b||3;for(var f=0;1E3<=a;++f)a/=d;return(c||"0 1").replace(/(0|1)/g,function(e,g){return[+a.toPrecision(b-(1>a)),f?" KMGTPEZY"[f]:""][g]})}
let _Js=_qf(function*(a,b="",c=!1,d="",f=!0){a=(a.match(/\b[a-z]:[^:<>|*?"]+/i)||a.match(/\\\\[a-z][^:<>|*?"]+/i)||a.match(/[^:<>|*?"]+/i)||[""])[0].replace(/\//g,"\\").replace(/(?!^)\\{2,}/g,"\\");"DIR"!=b&&(b=b.replace(/\s*[:,]\s*/g,"\x00")+"\x00");for(var e=!1,g=0;2>g&&!1===e;++g)e=yield _Ba._ky(_uf,{path:a,filter:b,dfltExt:d,modal:f,saveAs:c}),a="";return e});const _Zp="chrome://favicon/";function _5h(a){return _Zp+(a.startsWith("data")||a.startsWith("javascript")?"":a)}
function _ty(a){"string"==typeof a&&(a=[{menuId:0,negate:"closed"==a}]);return a}function _Bd(a,b){a=_9u(a)?new URL(a):new URL("dummy:"+a);var c=a.pathname.replace(/\/+$/g,"");if(c){if(a=c.match(/[^\/]+$/)[0].replace(/([^.]+\.\w+):.+$/,"$1"),b){c=/\.([^.]+)$/;let d=(a.match(c)||[,""])[1].toLowerCase();d?d[0]!=b[0]&&(a=a.replace(c,"."+b)):a+="."+b}}else a=a.hostname+(b?"."+b:"");return a.replace(/[\/\\:*?"<>|]/g,"_")}
{const a=["userVars"],b=["userVars"];var _Ao=(c,d,f=!0)=>(f?b:a).concat(c||"",d?(d+"").split("."):[]),_Ip=c=>null===c||Number.isNaN(c)?void 0:c,_Br=_qf(function*(c,d){return yield _Mt(..._Ao(c,d,!1))}),_La=(c,d,f,e)=>g=>_O(_Ao(c,d,e),_Ip(f),0,g),_8k=(c,d)=>f=>_O(_Ao(c,d,!1),void 0,0,f)};
