'use strict';const _6r={oper:"filter",params:{tgtExpr:"<windowId>",refExpr:"<windowId>"}},_hd={oper:"sort",params:{order:"mru",desc:!0}};
_tt.tse={other:{value:[]},currentTab:{name:"Current tab",help:"cur",value:""},prevUsedTab:{name:"Previous tab",help:"prv",value:[_6r,_hd,{oper:"filter",params:{pos:"next",wrap:!0}}]},nextUsedTab:{name:"Next tab",help:"nxt",value:[_6r,_hd,{oper:"filter",params:{pos:"prev",wrap:!0}}]},prevUsedTabAnyWin:{name:"Previous tab (any win.)",help:"prvAll",value:[_hd,{oper:"filter",params:{pos:"next",wrap:!0}}]},nextUsedTabAnyWin:{name:"Next tab (any win.)",help:"nxtAll",value:[_hd,{oper:"filter",params:{pos:"prev",
wrap:!0}}]},activeTabs:{name:"Active tabs",help:"act",value:[{oper:"filter",params:{tgtExpr:"<active>",refExpr:"true"}}]},activeTab:{name:"Active tab",help:"act0",value:[{oper:"filter",params:{tgtExpr:"<active>",refExpr:"true"}}]},openerTab:{name:"Opener tab",help:"opnr",value:[{oper:"filter",params:{tgtExpr:"<id>",refExpr:"<openerTabId>"}}]},leftTab:{name:"Left tab",help:"lft",value:[_6r,{oper:"filter",params:{pos:"prev"}}]},leftTabWrap:{name:"Left tab (wrap)",help:"",value:[_6r,{oper:"filter",params:{pos:"prev",
wrap:!0}}]},rightTab:{name:"Right tab",help:"rgt",value:[_6r,{oper:"filter",params:{pos:"next"}}]},rightTabWrap:{name:"Right tab (wrap)",help:"",value:[_6r,{oper:"filter",params:{pos:"next",wrap:!0}}]},firstTab:{name:"Leftmost tab",help:"",value:[_6r,{oper:"slice",params:{from:1,to:1}}]},lastTab:{name:"Rightmost tab",help:"",value:[_6r,{oper:"slice",params:{from:-1,to:-1}}]},newestTab:{name:"Newest tab",help:"nwst",value:[_6r,{oper:"sort",params:{order:"creation"}},{oper:"slice",params:{from:-1,to:-1}}]},
hoveredTabs:{name:"Hovered tab",help:"hvr",value:[{oper:"filter",params:{anyHvrd:!0}}]},allLeftTabs:{name:"All tabs to the left",help:"",multi:1,value:[_6r,{oper:"filter",params:{pos:"before"}}]},allRightTabs:{name:"All tabs to the right",help:"",multi:1,value:[_6r,{oper:"filter",params:{pos:"after"}}]},eventTabs:{name:"Event tab",help:"evt",value:[{oper:"filter",params:{evtTabs:!0}}]},highlighted:{name:"Selected tabs",help:"hlt",multi:1,value:[_6r,{oper:"filter",params:{tgtExpr:"<highlighted>",refExpr:"true"}}]},
pinnedTabs:{name:"Pinned tabs",help:"pin",multi:1,value:[_6r,{oper:"filter",params:{tgtExpr:"<pinned>",refExpr:"true"}}]},audibleTabs:{name:"Audible tabs",help:"aud",multi:1,value:[{oper:"filter",params:{tgtExpr:"<audible>",refExpr:"true"}}]},nonMinimTabs:{name:"Non-minimized tabs",help:"vsbl",multi:1,value:[{oper:"filter",params:{tgtExpr:"<window.state>",refExpr:"minimized",negate:!0}},{oper:"filter",params:{tgtExpr:"<window.state>",refExpr:"hidden",negate:!0}}]},otherTabs:{name:"Other tabs (curr. window)",
help:"othr",multi:1,value:[_6r,{oper:"filter",params:{tgtExpr:"<active>",refExpr:"false"}}]},otherTabsAllWins:{name:"Other tabs (all windows)",help:"othrAll",multi:1,value:[{oper:"filter",params:{tgtExpr:"<id>",refExpr:"<id>",negate:!0}}]},currWinTabs:{name:"All tabs (curr. window)",help:"",multi:1,value:[_6r]},currWinTabsMruOrder:{name:"All tabs (curr. window, MRU order)",help:"curWmru",multi:1,value:[_6r,_hd]},allTabs:{name:"All tabs (all windows)",multi:1,value:[]},allTabsMruOrder:{name:"All tabs (all windows, MRU order)",
help:"allMru",multi:1,value:[_hd]}};_tt.tse.add({righTab:_tt.tse.rightTab,righTabWrap:_tt.tse.rightTabWrap});
function _gr(b){if(!b.ufOper)return b;b.oper=b.ufOper;delete b.ufOper;let a=b.params||{};"string"==typeof a.refTab&&(a.refTab=_wf(_Np(a.refTab,"tse").value));"string"==typeof a.tabSet&&(a.tabSet=_wf(_Np(a.tabSet,"tse").value));if(a.compOper&&a.compOper.in("contains","starts","ends")){let d=("starts"==a.compOper?"^":"")+_Wt(a.refExpr||"","^$\\.*+?()[]{}|")+("ends"==a.compOper?"$":"");a.refExpr={templ:d,regex:!0}}delete a.compOper;a.tgtExpr&&(a.tgtExpr.in("prev","next","before","after")?(a.pos=a.tgtExpr,
delete a.tgtExpr):"openerTabId"==a.tgtExpr?(a.tgtExpr="<openerTabId>",a.refExpr="<id>"):"windowId"==a.tgtExpr?a.tgtExpr=a.refExpr="<windowId>":"groupId"==a.tgtExpr?a.tgtExpr=a.refExpr="<groupId>":"favList"==a.tgtExpr?delete a.tgtExpr:"evtTabs"==a.tgtExpr&&(delete a.tgtExpr,a.evtTabs=!0));"reverse"==a.order&&(b.oper=a.order);return b}const _5e=new WeakMap;let _0f=0;
function _Qf(b,a=!0){"string"==typeof b&&(b=_Np(b,"tse").value);if(!b)return b;if(a&&_5e.has(b))return _5e.get(b);const d=b;b=_wf(b);for(let c of b)_gr(c),"filter"==c.oper?(c.params.tgtExpr=_Yr(c.params.tgtExpr),c.params.refExpr=_Yr(c.params.refExpr),c.params.refTab=_Qf(c.params.refTab,!1)):"sort"==c.oper?c.params.order=_Yr(c.params.order):"addSet"==c.oper?(++_0f,c.params.tabSet=20<_0f?[]:_Qf(c.params.tabSet,!1),--_0f):"groupBy"==c.oper&&(c.params.expr=_Yr(c.params.expr));a&&_5e.set(d,b);return b}
function _zk(b,a){return _Qj(_Qf(b),a)}function _Qj(b,a){if(!b)return _7h?[[_7h]]:[[]];a=a?a.slice():[_wl];a[0]||(a[0]=[]);for(let d of b)d.oper&&(a=_Au(a,d.oper,d.params),a[0]||(a[0]=[]));return a}function _Ga(b){return[...new Set(_3g(...b))]}function _E(b,a,d){a=Math.max(1,(a||1)+(0>a?b.length+1:0))-1;d=Math.max(a,(d||b.length)+(0>d?b.length+1:0));return b.slice(a,d)}
function _Au(b,a,d){if("mergeGrp"==a)return[_Ga(b)];if("addSet"==a){var c=_Qj(d.tabSet);return d.replace?c:b.concat(c)}if("slice"==a&&d.groupWise)return _E(b,d.from,d.to);if("reverse"==a&&d.groupWise)return b.slice().reverse();c=[];a=_ju[a];for(let e of b)c.push(...e.length?a(e,d):[]);return c}const _ju={filter:_gk,posFilter:_gk,sort:_7k,groupBy:_vu,reverse:b=>[b.slice().reverse()],slice:(b,a)=>[_E(b,a.from,a.to)]};
function _7k(b,a){let d=a.order;a=a.desc;switch(d){case "normal":b=_ls(b,_wl);break;case "mru":b=_ls(b,_Yk,!0);break;case "zOrder":b=_pe(b);break;case "creation":b=_ls(b,_gd,!0);break;default:let c={};for(let e of b)c[e]=_n(d,_ts[e]);b=b.slice().sort((e,f)=>{e=c[e];f=c[f];return e==f?0:e<f?-1:1})}a&&b.reverse();return[b]}
function _pe(b){if(_Of)return _hj.addFunc(_Uw(function*(){_Of&&(yield _ky(_Ay),_Of=!1)})),b.slice();let a=0;for(let d of _ou)_pj[d].zIndex=a--;_Yk=_ls(_wl,_Yk,!0);for(let d of b)_ts[d].mruIndex=_Yk.indexOf(d);return b.slice().sort((d,c)=>{let e=_ts[d].window.zIndex-_ts[c].window.zIndex;return e?e:_ts[d].mruIndex-_ts[c].mruIndex})}
function _vu(b,a){let d=_Eh();for(let c of b){if("overlapArea"==a.expr){let e=_8e(_ts[c].window);b=0;for(let [,f]of d){let h=_8e(_ts[f[0]].window);if(_kh(_6p(e),h)||_kh(_6p(h),e))break;++b}}else b=_n(a.expr,_ts[c]);d[b]||(d[b]=[]);d[b].push(c)}return[...d].map(([,c])=>c)}let _Rt;function _Zj(){if(_Rt)return _Rt;_hj.addFunc(_Uw(function*(){_Rt=yield _ky(_Rj,{usePrvMsPos:!!_xu(_Dt).usePrevMousePos})}));return{}}
function _0(b=!1,a=!1,d=!1){const c={TSE:g=>_3g(..._zk(g)),tabList:g=>g,tab:g=>[g]};let e=[],f=g=>{(g=_op(g))&&g.type in c&&e.push(...c[g.type](g.content))},h=_Zj();b&&h.marked&&f(h.marked);a&&h.hilited&&f(h.hilited);d&&h.hovered&&f(h.hovered);return[...new Set(e)].filter(g=>g in _ts)}
function _gk(b,a){let d=[],c;a.favList?c=_0k[a.favList]||[]:a.evtTabs?c=_sw(_Dt):"menuSeltn"==a.tgtExpr?c=_0(a.marked,a.hilited,a.hovered):a.anyHvrd&&(c=_0(!1,!1,!0),c.length||(c=_pt(),c.length||(c=[_kd(_pj,_Mu(),"activeTab","id")])));if(c)d=b.filter(f=>0<=c.indexOf(f)==!a.negate);else{var e=_ts[a.refTab?_Qj(a.refTab,[b])[0][0]:_7h];if(e)if(a.pos)d=_Ak(b,a,e.id),a.negate&&(d=b.filter(f=>-1==d.indexOf(f)));else{e=_n(a.refExpr,e);for(let f of b)b=_n(a.tgtExpr,_ts[f]),(b instanceof RegExp?b.test(e):
e instanceof RegExp?e.test(b):String(b)==String(e))==!a.negate&&d.push(f)}}return[d]}function _Ak(b,a,d){var c=b.indexOf(d);if(0>c)return[];b=[b.slice(0,c),b.slice(c+1).reverse()];c=a.pos.in("before","prev");let e=b[+!c].reverse();a.addRef&&e.unshift(d);a.wrap&&(e=e.concat(b[+c]));a.pos.in("prev","next")&&(e=e.slice(0,1));return e};
