'use strict';const _Bk={[_iw]:{name:"Tab opens",title:"A tab is opened",help:"opn"},[_Pk]:{name:"Tab closes",title:"A tab is closed",help:"cls"},[_5w]:{name:"Tab activates",title:"A tab is activated",help:"act"},[_oe]:{name:"Tab deactivates",title:"A tab is deactivated",help:"dAct"},[_Ly]:{name:"Tab focuses",title:"A tab is focused",help:"foc"},[_My]:{name:"Tab unfocuses",title:"A tab is unfocused",help:"uFoc"},[_ho]:{name:"Tab load begins",title:"A tab starts loading a page",help:"ldB"},[_7a]:{name:"Tab load ends",
title:"A tab finishes loading a page",help:"ldE"},[_oo]:{name:"Tab unloads",title:"A tab's content is unloaded",help:"uld"},[_Ht]:{name:"Tab URL changes",title:"A tab's URL changes",help:"uChg"},[_jr]:{name:"Tab audio starts",title:"A tab starts playing audio",help:"audB"},[_lh]:{name:"Tab audio stops",title:"A tab stops playing audio",help:"audE"},[_vk]:{name:"Window opens",title:"A window is opened",help:"wOpn"},[_yf]:{name:"Window closes",title:"A window is closed",help:"wCls"},[_te]:{name:"Window focuses",
title:"A window is focused",help:"wFoc"},[_ed]:{name:"Window unfocuses",title:"A window is unfocused",help:"wUnf"},[_ms]:{name:"Window minimizes",title:"A window is minimized",help:"min"},[_nw]:{name:"Window unminimizes",title:"A window is unminimized",help:"uMin"},[_yu]:{name:"Toolbar btn",title:"A toolbar button is clicked",help:"tbb"},[_Ta]:{name:"Clipbrd changes",title:"The clipboard changes",help:"cbC"},[_8a]:{name:"External event",title:"External app event",help:"ext"},[_og]:{name:"On startup",
title:"AutoControl starts up",help:"stu"}};function _2s(l){l=_T(l);return l.type==_Wd?_Uj(l.num)?_Bk[_yu].name+" "+_6o(l.num-_yu):_Bk[l.num].name:l.isDownUp?_cj(l.num):""}
let _Oh=(()=>{function l(a){if(a.mouseMove)var b="<gest>"+a.mouseMove+"</gest>";else{var c=a.eventId||a.keyEvt;if(c&&(b=_2s(c),c=_T(c)))if(c.type!=_Wd){var d=c.type==_Lw?a.toggleState?"off":"up":a.toggleState?"on":"down";a.holdPeriod&&(d+=" hold")}else if(_Uj(c.num))var e="iconUID=TBBtn"+(c.num-_yu),f={[_Ci]:"L",[_1t]:"R",[_Ok]:"M",[_Pg]:"4th",[_Vu]:"5th"}[a.btnId];else c.num==_8a&&a.evtName&&(b=`<b>Extern:</b> <n>${a.evtName}</n>`)}if(b){c=_Le;var k=a.mouseMove?_Ls:_q(a.eventId||a.keyEvt);a=`<event class="${c(k)} ${d||
""}" ${e||""} title="Click for options">${b}<d>${f||""}</d>${1<a.repCount?"<r>"+a.repCount+"</r>":""}</event>`}else a="";return a}function y(a,b,c){delete a.eventId;delete a.voiceCmd;delete a.block;delete a.btnId;"E"==b?(delete a.mouseMove,b=_T(c),a.eventId=c,a.block=c.in(_1t,_Pg,_Vu)?_Hd:c==_Ci&&a.preconds.length||!c.in(_Ci,_Uk,_ri,_rw,_Oy,_zg,_C)?_bt:_Q,b.type!=_Wd||_Uj(b.num)||a.wildcard!=_go||0!=a.preconds.length||(a.wildcard=_hi)):"G"==b&&(delete a.holdPeriod,delete a.repCount,b=_eu(c.state),
"I"==b?a.mouseMove="":"C"==b?a.mouseMove+=_eu(c.dir):"S"!=b||a.mouseMove||J(a))}function K(a){a=_T(a,!0);return a.isDownUp&&(a.devId!=_Ls||!("miscNum"in a))}function z(a,b){b=_T(b);if(!b.isDownUp)return!1;for(let c of a.preconds||[])if(_T(c.keyEvt).num==b.num)return!0;return(a=_T(a.eventId))&&a.isDownUp&&a.num==b.num}function p(a){var b=a.closest("trigger");b=_Zg(b);a=$(a).closest("triggers")[0].value;return _ng(a,b)}function q(a){a=$(a).closest("combin")[0];return _ng(p(a),"combins",_Zg(a))}function A(a){var b=
$(a).closest("combin");let c=q(b);b=b.find("event");a=b.index(a);return a==b.length-1?c:c.preconds[a]}function B(a){$(">cont",a).html(L(q(a)))}function C(a,b,c,d){if(!$("gestAssistPane")[0]||"G"==b){var e=q(a);{let f=_ng(e,"preconds",[]);e.eventId&&K(e.eventId)?"E"==b&&z(e,c)||(f.push({keyEvt:e.eventId}),y(e,b,c)):e.eventId||e.mouseMove?"E"==b&&K(c)?z(e,c)||f.push({keyEvt:c}):y(e,b,c):y(e,b,c)}d&&e.add(d);B(a);c.in(_Ci,_Ci|_Lw)&&u(a,!1)}}function W(a){let b=c=>{let d=_Bk[c];return`<div evtId=${c}>${d.title} ${d.help?
`<h h=${d.help}></h>`:""}</div>`};return $(`\n <envEvtsMenu helpCtx=env/evts>\n <group>\n ${b(_yu)}\n <hr>\n ${b(_iw)}\n ${b(_Pk)}\n ${b(_5w)}\n ${b(_oe)}\n ${b(_Ly)}\n ${b(_My)}\n <hr>\n ${b(_ho)}\n ${b(_7a)}\n ${b(_oo)}\n ${b(_Ht)}\n </group>\n <group>\n ${b(_Ta)}\n <hr>\n ${b(_jr)}\n ${b(_lh)}\n <hr>\n ${b(_vk)}\n ${b(_yf)}\n ${b(_te)}\n ${b(_ed)}\n ${b(_ms)}\n ${b(_nw)}\n <hr>\n ${b(_og)}\n <!--\n ${b(_8a)}\n -->\n </group>\n </envEvtsMenu>\n `).on("click","div[evtId]",_ug(function*(c){c=+$(this).attr("evtId");
if(c==_yu){var d=yield _Jf();if(d.length)c+=d[0],d={btnId:_Ci};else return _2("You haven't added any toolbar buttons yet. <br> Go to the <b>Options</b> tab, under section <b>Custom Toolbar Buttons</b>.")}$(this).triggerEvt("focusLost",!0);C(a,"E",c|_Wd,d)}))}function D(a){let b=$(a).closest("triggers").is("[gestureConf]"),c=$(`\n <combEditBar popupCntr title="">\n <cont>\n <bar1><h h=${b?"edtCmbG":"edtCmb"}></h></bar1>\n <bar2>\n <btn gest title="Enter a mouse gesture">\n <i mouseGestDirs dirs></i>\n </btn>\n <btn evts>Events</btn>\n </bar2>\n </cont>\n </combEditBar>\n `);
c.on("mousedown","btn[gest]",function(d){v(!0,d)}).on("mousedown","btn[evts]",function(){_aw(W(a),this,"brlt","tailAndShadow noTail")}).on("mousedown",function(d){d.stopPropagation()});setTimeout(()=>{$(window).captureEvt("mousedown.combinEdit",function(d){if(!v(!1)){d=$(d.target);var e;d.closest("combEditBar")[0]||d.closest("envEvtsMenu")[0]||(d.closest("combin.edit event")[0]?E():(e=d.closest("combin.edit")[0])?C(e,"E",_Ci):E())}}).on("blur.combinEdit",()=>E())},150);$(a).closest("triggers").addClass("editing");
$(a).append(c).addClass("edit").css("min-width",$(a).css("width"));z(q(a),_Ci)||u(a,!0);_Ba._5s(!0,(d,e)=>{let f;"E"==d&&(e==(_1t|_Lw)||e==_1t&&(f=$(":hover").last().closest("combin.edit event")[0]))?e==_1t&&M(f,!1):C(a,d,e)});_Mt("mouseGest","params","dirPrecision")(d=>{$("[dirs]",c).attr("dirs",d||8)});c.enableResizeEvent().on("resize",function(){$("btn[gest], h",this).triggerEvt("resize")});setTimeout(()=>{let d=$("trigActList combin");1==d.length&&d.is(".edit")&&0==$("event",d).length&&0==$(".popup",
c).length&&!_Vt&&$("h",c).triggerEvt({mousedown:!0})},400)}function u(a,b){$(a).toggleClass("lftBtnInput",b).attr("title",b?"A Left click here enters a Left Btn.":"")}function E(){if(0!=$("combin.edit").length){v(!1);_Ba._5s(!1);$(window).off(".combinEdit").delEvtCapture(".combinEdit");var a=$("combin.edit:has(>combEditBar)");a.length&&(a.closest("triggers").removeClass("editing"),a.removeClass("edit").css("min-width","").find(">combEditBar").remove(),u(a,!1),_Yo(a),0==$("> cont > event",a).length?
F(a[0]):a.closest("trigger").removeClass("empty"))}}function F(a){let b=p(a);b.combins.splice(_Zg(a),1);_Yo(a);$(a).closest("trigger").toggleClass("empty",!b.combins.length);$(a).closest("combinSeq").html(w(b.combins))}function M(a,b=!0){var c=A(a);let d=$(a).closest("combin")[0];(c.eventId||c.keyEvt||0).in(_Ci,_Ci|_Lw)&&u(d,!0);if(c.keyEvt)a=q(a),c=a.preconds.indexOf(c),a.preconds.splice(c,1);else if(!J(c)&&b)return F(d);b&&_Yo(d);B(d)}function J(a){let b=(a.preconds||[]).pop();delete a.eventId;
delete a.mouseMove;delete a.voiceCmd;return b?(a.eventId=b.keyEvt,a.block=!0):!1}function X(a){return $(`\n <gestAssistPane>\n <p1 hl>Move your mouse now.</p1>\n <p1>Once your gesture is done,<br>finish with <u>left click</u>.</p1>\n <p2>\n <p2a>Gesture precision:<v dirs=${a}>directions<i mouseGestDirs dirs=${a}></i></v></p2a>\n <p2b>(change this in the options tab)</p2b>\n </p2>\n </gestAssistPane>\n `)}function Y(a){this.svg=_Ze("mouseGestureCanvas",void 0,t).appendTo("body")[0];this.polyline=$(">polyline",
this.svg)[0];this.addPoint=function(b,c){let d=this.svg.createSVGPoint();d.x=b;d.y=c;this.polyline.points.appendItem(d)};this.addPoint(a.x,a.y);this.mouseMoveCallback=b=>{this.addPoint(b.clientX,b.clientY)};$(document).on("mousemove",this.mouseMoveCallback);this.destroy=function(b=1E3){$(document).off("mousemove",this.mouseMoveCallback);$(this.svg).css({transition:b+"ms opacity",opacity:0,pointerEvents:"none"});setTimeout(()=>{$(this.svg).remove();delete this.svg},b)}}function n(a){let b=$(l(A(a)))[0];
a.popupElem&&(a.popupElem.popupTriggerElem=$(b).prop("popupElem",a.popupElem).addClass("popup")[0]);$(a).replaceWith(b);return b}function Z(a){a=_T(a);return a.isDownUp&&a.num.in(_M,_ch,_Er)}function aa(a){let b=_Ze("combinOptionsPane",void 0,t),c=q(a),d=_T(c.eventId)||{};d.type!=_Wd||_Uj(d.num)||$("div[wildcard]",b).addClass("envEvt");$("div[wildcard] select",b).val(c.wildcard||_lo).change(function(){c.wildcard=+this.value;B(a);$(this).triggerEvt("resize",!0);_Yo(a)});$(a).is(":not(:first-of-type)")&&
$("div[maxTime]",b).css("display","block").find("input").prop("value",c.maxTime||"").change(function(){(c.maxTime=+this.value)||delete c.maxTime;_Yo(a)});$(a).is(":not(:first-of-type)")&&$("div[antiSeq]",b).css("display","block").find("input").prop("checked",c.negateSeq).change(function(){c.negateSeq=this.checked;$(a).prevAll("sep:first").toggleClass("negate",this.checked);_Yo(a)});$("btn[del]",b).dblclick(function(){$(this).triggerEvt("focusLost",!0);F(a)});$("btn[edit]",b).click(function(){$(this).triggerEvt("focusLost",
!0);D(a)});return b}function N(a){let b=p(a),c=_Zg(a);_ng(b,"combins",[]).splice(c,0,{wildcard:_go});a=$(a).closest("combinSeq").html(w(b.combins)).find(">combin").eq(c)[0];D(a)}function L(a){var b={[_go]:"",[_hi]:"<wc>*</wc>",[_kg]:'<event class="keybrd wc">*</event>',[_cr]:'<event class="mouse wc">*</event>'};b=(b=a.wildcard in b?b[a.wildcard]:"<wc>**</wc>")?b+" + ":"";for(let c of a.preconds||[])b+=l(c)+" + ";return b+l(a)}function w(a){let b="";if(!a.length)return"<combin class=empty>Enter a trigger for the action</combin>";
for(let c=0;c<a.length;++c){let d=a[c];b+=`\n <sep button actBtn hh=newCmb class="${d.negateSeq?"negate":""}"></sep>\n <combin><cont>${L(d)}</cont><b></b></combin>\n `}return b+"<sep button actBtn hh=newCmb></sep>"}function G(a,b="urlTests"){let c=_kd(a,"preconds",b),d="evtUrl"==b;return _7p(c)||d&&!O(a)?"":_Ww`\n <precondMulti name=${b} value=[]>\n <wrap>\n <l>${"evtUrl"==b?"Event ":""}URL:</l>\n <content>${c.map(ba)}</content>\n </wrap>\n <h h="${d?"evtUrl2":"urlPr2"}"></h>\n </precondMulti>\n `}
function ba(a){return`\n <urlTest precond value={}>\n ${_1u([[_8f,["Whole URL","full"]],[_Vs,["Domain","dom"]],[_lp,["Main domain","mDom"]],[_rk,["Path","pth"]]],"part",a.part,"","number helpCtx")}\n ${_1u({0:["does","ds"],1:["doesn't","dnt"],[_5d]:["must","mst"]},"negate",a.negate,"","number helpCtx")}\n ${_Mo({equals:"match exactly",contains:"contain",starts:"start with",ends:"end with"},a.type,"type")}\n ${_ba("value",a.value,"Enter text","autoDim")}\n <del button>&#xD7;</del>\n </urlTest>\n `}
function P(a){return(a=_kd(a,"preconds","chromeState"))?`\n <precond name=chromeState value={}>\n <wrap>\n Browser state:\n <label>${_Gy("active",a.active)}<l>Focused</l></label>\n <label>${_Gy("inactive",a.inactive)}<l>Unfocused</l></label>\n <label>${_Gy("closed",a.closed,"perms=bg")}<l>Closed</l></label>\n <del button>&#xD7;</del>\n </wrap>\n <h h=brwSt></h>\n </precond>\n `:""}function Q(a){return(a=_kd(a,"preconds","caretState"))?`\n <precond name=caretState value={}>\n <wrap>\n Text cursor:\n <label>${_Gy("on",
a.on)}<l>On</l></label>\n <label>${_Gy("omnibox",a.omnibox)}<l>Omnibox</l></label>\n <label>${_Gy("off",a.off)}<l>Off</l></label>\n <del button>&#xD7;</del>\n </wrap>\n <h h=crtSt></h>\n </precond>\n `:""}function R(a){a=_ty(_kd(a,"preconds","menuState"));return _7p(a)?"":_Ww`\n <precondMulti name=menuState value=[]>\n <wrap>\n <l>Menu:</l>\n <content>${a.map(b=>`\n <menuState precond value={}>\n ${_Ws("menuSpec","menuId",b.menuId,"(any menu)","(any menu)",!1,!1)}\n ${_Mo({0:"is open",1:"isn't open"},
b.negate,"negate","bool hard")}\n <del button>&#xD7;</del>\n </menuState>\n `)}</content>\n \n <!--label>\${makeRadioButton(true, 'open', state)}<l>Visible</l></label>\n <label>\${makeRadioButton('', 'closed', state)}<l>Not visible</l></label-->\n </wrap>\n <h h=menuSt></h>\n </precondMulti>\n `}function S(a){a=_kd(a,"preconds","mouseOver");return _7p(a)?"":_Ww`\n <precondMulti name=mouseOver value=[]>\n <wrap>\n <l>Mouse:</l>\n <content>${a.map(b=>`\n <mouseOver precond value={}>\n ${_Mo({or:"Over",
not:"Not over"},b.oper,"oper")}\n ${_7y(T,"mseOvrRegions","region",b.region,void 0,"number helpCtx")}\n <del button>&#xD7;</del>\n </mouseOver>\n `)}</content>\n </wrap>\n <h h=mseOvr></h>\n </precondMulti>\n `}function U(a){a=_kd(a,"preconds","swtchState");return _7p(a)?"":_Ww`\n <precondMulti name=swtchState value=[]>\n <wrap>\n <l>Switch:</l>\n <content>${a.map(b=>`\n <swtchState precond value={}>\n ${_5f("swtchId",b.swtchId)}\n ${_Mo({1:"is ON",0:"is OFF"},b.state,"state","bool hard")}\n ${_Mo({"&":"AND",
"|":"OR","=":"EQUAL"},b.oper,"oper")}\n <del button>&#xD7;</del>\n </swtchState>\n `)}</content>\n </wrap>\n <h h=swchSt></h>\n </precondMulti>\n `}function V(a={}){return`\n <trigger ${_7p(a.combins)?"class=empty":""}>\n <ctrl><del button title="Delete this trigger">&#xD7;</del></ctrl>\n <combinSeq>${w(a.combins||[])}</combinSeq>\n <preconds value={}>\n ${P(a)}\n ${Q(a)}\n ${G(a)}\n ${G(a,"evtUrl")}\n ${S(a)}\n ${R(a)}\n ${U(a)}\n </preconds>\n <add button title="Add a condition">Condition</add>\n ${_Cs(a)?
"\n <foreign>\n <cont>\n This is a global trigger being synchronized from another AutoControl installation. <hr b>\n Enable the trigger only if you understand the consequences. <br>\n <div> <h h=enTrig></h> <button>Enable trigger</button> </div>\n </cont>\n </foreign>\n ":""}\n </trigger>\n `}function O(a){return(a=_T(_kd(a.combins,-1,"eventId")))&&a.type==_Wd&&a.num<_Qu}function ca(a){let b=p(a);return $(`\n <precondsMenu>\n <item value=urlTests>URL <h h=urlPr></h></item>\n ${O(b)?"<item value=evtUrl>Event URL <h h=evtUrl></h></item>":
""}\n <item value=chromeState ${_kd(b,"preconds","chromeState")?"greyedout":""}>Browser state <h h=brwSt></h></item>\n <item value=caretState ${_kd(b,"preconds","caretState")?"greyedout":""}>Text cursor <h h=crtSt0></h></item>\n <item value=mouseOver>Mouse over <h h=mseOvr></h></item>\n <item value=menuState>Menu state <h h=menuSt></h></item>\n <item value=swtchState>Switch state <h h=swchSt0></h></item>\n </precondsMenu>\n `).on("click","item",function(){let c=$(this).attr("value"),d=a.closest("trigger");
var e=p(d);if(c.in("urlTests","evtUrl")){let k=_ng(e,"preconds",c,[]);if(!k.length||Object.keys(k[k.length-1]).length){k.push({part:_8f,negate:0});var f=G(e,c)}}else"chromeState"==c?(_ng(e,"preconds",c).active=!0,f=P(e)):"caretState"==c?(_ng(e,"preconds")[c]={on:!0,off:!0,omnibox:!0},f=Q(e)):"menuState"==c?(f=_ty(_kd(e,"preconds","menuState"))||[],_ng(e,"preconds",c,f).push({menuId:0,state:!0}),_Yo(this),f=R(e)):"mouseOver"==c?(_ng(e,"preconds",c,[]).push({region:_Ah}),_Yo(this),f=S(e)):"swtchState"==
c&&(_ng(e,"preconds",c,[]).push({state:!0}),f=U(e));f&&(e=f,f=$(e).attr("name"),f=$(`preconds [name=${f}]`,d),f[0]?f.replaceWith(e):$("preconds",d).append(e));c.in("urlTests","evtUrl")&&$("urlTest:last-of-type input",d).focus();$(this).triggerEvt("focusLost",!0)}).on("close",function(){this.remove()})}const t=document.currentScript.parentElement,da=(a,b)=>_Ze(a,b,t);{let a=!1,b;var v=function(c,d){if(c!=a&&(c||b)){a=c;_Ba._Ya(_qe,a);c=$("combEditBar btn[gest]");var e=c.closest("trigAct");if(e[0]){var f=
e.find("+ sep");a?(_aw(X($("[dirs]",c).attr("dirs")),c,"bltr","tailAndShadow noTail"),e.css({width:e.css("width"),top:e[0].offsetTop}).addClass("offline"),f.css(e.css(["width","height"])),_Oa(()=>b=new Y({x:d.clientX,y:d.clientY}))):(e.add(f).removeClass("offline").css({width:"",height:""}),b.destroy(700),b=null);return!0}}}}let fa=_ug(function*(a,b){let c=_Ze("eventOptionsPane",void 0,t),d=A(a),e=_T(d.eventId||d.keyEvt,!0);if(e&&e.devId==_zd){var f=_kd(_Fk,e.num,1);if(f){$("div[variant]",c).css("display",
"block").change(function(g){let h="eventId"in d?"eventId":"keyEvt";d[h]=g.target.value|_T(d[h]).type;a=n(a);_Yo(a)});f=_0p(f)?e.num:f;var k=_Fk[f][1],H=c.find("div[variant] select")[0];for(var m of[k[0],k[1],f])H.options.add(new Option((m==f?"Any ":"")+_Fk[m][0],m,!1,m==e.num))}}m=_Jd(e);d.eventId&&(f=+(e.type==_Lw),m?($("div[action], div[holdDown]",c).css("display","block"),$("div[action] select",c).val(f).change(function(){let g=$("div[block] select:visible",c)[0];if(g){const h=+g.value;1==+this.value&&
h&&!g.noAutoUncheck&&(g.value=_Q,$(g).triggerEvt("change",!0),g.prevValue=h);0==+this.value&&(h?g.noAutoUncheck=!0:g.prevValue&&(g.value=g.prevValue,$(g).triggerEvt("change",!0)))}d.eventId=_T(d.eventId).num|(+this.value?_Lw:_qa);$("div[holdDown]",c).attr("greyedout",+this.value?"":null);$("div[autoRep]",c).attr("greyedout",+this.value||e.devId!=_zd&&!d.holdPeriod?"":null);a=n(a);_Yo(a)}),$("div[holdDown] input",c).val((d.holdPeriod|0)/1E3).change(function(){d.holdPeriod=1E3*this.value;$("div[autoRep]",
c).attr("greyedout",e.devId==_zd||d.holdPeriod?null:"");a=n(a);_Yo(a)}),f&&$("div[holdDown]",c).attr("greyedout",""),(f||e.devId!=_zd&&!d.holdPeriod)&&$("div[autoRep]",c).attr("greyedout","")):e.devId==_Ls&&$(`div[${e.num==_Zr?"vertDir":"horzDir"}]`,c).css("display","block").find("select").val(f).change(function(){d.eventId=_T(d.eventId).num|(+this.value?_Lw:_qa);a=n(a);_Yo(a)}),m&&$(a).closest("combin").is(":last-of-type")&&$("div[autoRep]",c).css("display","block").find("input").prop("checked",
d.noAutoRep).change(function(){d.noAutoRep=this.checked;_Yo(a)}));d.keyEvt&&($("div[state]",c).css("display","block"),Z(d.keyEvt)&&$("div[state]",c).addClass("lockKey"),f=+(e.type==_Lw)+2*(d.toggleState|0),$("div[state] select",c).val(f).change(function(){d.keyEvt=_T(d.keyEvt).num|(this.value&1?_Lw:_qa);d.toggleState=!!(this.value&2);$("div[block]",c).attr("greyedout",0<this.value?"":null);a=n(a);_Yo(a)}),0<f&&$("div[block]",c).attr("greyedout",""),f=$("div[block] h",c),f.attr("h",f.attr("h2")));
d.eventId&&e.isDownUp&&($("div[repeat]",c).css("display","block"),$("div[repeat] input",c).val(d.repCount||1).change(function(){d.repCount=+this.value;a=n(a);_Yo(a)}));e&&e.devId.in(_zd,_Ls)&&($("div[block]",c).css("display","block").toggleClass("prsblBtn",m),$("div[block] select",c).val(+d.block||0).focus(function(){this.lastValue=this.value}).change(_ug(function*(g){this.blur();var h=g.originalEvent.isTrusted,r=_T(d.eventId,!0)||{};const x=r.type==_Lw&&_Jd(r);var I=0==_Zg($(a).closest("combin"));
g=+this.value;I=r.num==_Ci&&(!x&&g!=_Q||x&&g==_Hd)&&_7p(d.preconds)&&I;r=g==_bt&&x&&!this.noAutoUncheck;h&&(r||I)?(h=e.devId==_zd?"key":"button",this.value=this.lastValue||_Q,r?h=yield _Dg("",da("overrideReleaseWarning",{keyName:h}),{yes:"I understand, override anyway",no:"Don't override",icon:"warning",width:"initial"}):(yield ea=>_2(_Ze("overrideLeftBtnWarning",void 0,t),{width:"initial"},ea),h=!0),h&&(this.value=g,$(this).triggerEvt("change",!0))):(h&&this.lastValue==_bt&&(delete this.prevValue,
x&&(this.noAutoUncheck=!0)),d.block=g,_Yo(a))})));m=(k=e&&e.type==_Wd)&&_Uj(e.num);f=k&&e.num==_8a;k=k&&e.num==_Ta;if(m){H={}.add((yield _Jf()).map(h=>[h,`<c iconUID=TBBtn${h}>Button ${_6o(h)}</c>`]));let g={0:"Left click",[_Ci]:"Left press",[_1t]:"Right press",[_Ok]:"Middle press",[_Pg]:"4th press",[_Vu]:"5th press"};$(`\n <div style="display: block"><l>Toolbar btn:</l> ${_1u(H,"",e.num-_yu,"","number")} <h h=tbBtnSel></h></div>\n <div style="display: block"><l>Method:</l> ${_Mo(g,d.btnId,"btnId",
"number")} <h h=tbBtnMtd></h></div>\n `).prependTo(c).change(h=>{"btnId"==h.target.name?d.btnId=_Me(h.target):d.eventId=_Me(h.target)+_yu|_Wd;a=n(a);_Yo(a)})}else k?$(`\n <div style="display: block">&nbsp; Content: ${_Mo([[0,"(any type)"],[_qd,"Text"],[_3y,"Formatted text"],[_xf,"Image"],[_Ks,"Files/Folders"]],d.clipFmt,"clipFmt","number")} <h h=clpFmt></h></div>\n <div style="display: block"><label>${_Gy("diffCont",d.diffCont)}Only if different content</label> <h h=clpDiff></h></div>\n `).prependTo(c).change(g=>
{d[g.target.name]=_Me(g.target);a=n(a);_Yo(a)}):f&&$(`\n <div style="display: block">&nbsp; Event name: ${_ba("evtName",d.evtName)} <h h=evtn></h></div>\n `).prependTo(c).change(g=>{d.evtName=g.target.value;a=n(a);_Yo(a)});!d.mouseMove&&e&&(e.devId!=_9k||m||k||f)&&$("noParams",c).hide();d.mouseMove||$("[editGest]",c).hide();$("btn[del]",c).dblclick(function(){$(this).triggerEvt("focusLost",!0);M(a)});$("[editGest]",c).click(function(g){$(this).triggerEvt("focusLost",!0);let h=$(a).closest("combin");
D(h);setTimeout(()=>v(!0,g))});b(c)}),T={mseOvrRegions:_Eh([[_Ah,["Browser window","brwW"]],[_nh,["Web page","webP"]],[_Uh,["Title area","titA"]],[_Wk,["Browser tab","tab"]],[_5k,["Tab's close button","tabX"]],[_wi,["Tab's speaker icon","tSpk"]],[_hr,["New tab button","ntb"]],[_1g,["Toolbar","tBar"]],[_1k,["Omnibox","omnb"]],[_ss,["Bookmark button","bmrk"]],[_mh,["Browser menu button","brMn"]],[_5p,["Any menu item","miA",!0]],[_eo,["Menu item: tab","miTb"]],[_vw,["Menu item: tab submenu","miTG"]],
[_ly,["Menu item: closed tab","miCT"]],[_Ae,["Menu item: closed window","miCW"]],[_Jg,["Menu item: bookmark","miBK"]],[_Ti,["Menu item: bookmark folder","miBF"]],[_Xw,["Menu item: action","miAc"]],[_hu,["Menu item: switch","miSw"]]])};return{make:function(a=[],b="",c={}){0==a.length&&a.push({});return _Ww`\n <triggers trigOrAct DataModule helpCtx="/triggers" popupCntr ${_7p(_kd(a,0,"combins"))?"class=empty":""} name="${b}" value=$${a} ${c.extraAttrs||""}>\n <header>${c.title||"Trigger"} <selector><list></list><add button actBtn hh=addTrg></add></selector></header>\n <content>${a.map(V)}</content>\n </triggers>\n `},
setEvtLtnrs:function(a){_ng($(a)[0],"optionsCollection").add(T);return $(a).attr("optionsCollection","").on("click","combinSeq sep",_F(-400,function(){N(this)})).on("mousedown","combinSeq combin.empty",function(){N(this)}).on("mousedown","combin:not(.edit) event:not(.popup)",function(b){fa(this,c=>_aw(c,this,"btrl","tailOnly noTail"));b.stopImmediatePropagation()}).on("contextmenu","combin event",!1).on("mousedown","combin:not(.empty):not(.edit)",function(){let b=aa(this);_aw(b,this,"b)t)r<l<","tailOnly noTail")}).on("mousedown",
"preconds + add",function(){_aw(ca(this),this,"btrl","borderAndShadowSimple noTail")}).on("click","precond [type=checkbox]",function(b){0==$(this).closest("precond").find("input:checked").length&&(b.preventDefault(),b.stopImmediatePropagation(),setTimeout(()=>this.clickCount=0,2E3),this.clickCount=(this.clickCount|0)+1,this.helpBubble||3!=this.clickCount||(this.helpBubble=_aw("<help noPopupAround dontCloseOnFocusLost><nobr>At least 1 option must be selected</nobr></help>",this,"btrl","infoBubble small",
"","opacity"),setTimeout(()=>{$(this.helpBubble).triggerEvt("close");this.helpBubble=null},2500)))}).on("change","preconds",function(b){p(this).preconds=_Me(this);_Yo(this)}).on("click","preconds [name=chromeState] input",function(b){"closed"==this.name&&_By("trigActList.*.triggers","mouseGest.triggers.*",c=>{_rt(c)});if(_Ba._Rh){b=p(this);let c=_Me(this.closest("[name=chromeState]"));_ng(b,"author",_Ba._Dh,c.inactive||c.closed?1:void 0,NaN)}}).on("dblclick","[precond] > del, precond del",function(){let b=
$(this).closest("precond, [precond]");"chromeState"==b.attr("name")&&_By("trigActList.*.triggers","mouseGest.triggers.*",c=>{_rt(c)});_sy(b)&&_Pj(500);b.is(":only-of-type")&&(b=b.closest("preconds > *"));b.parent().triggerEvt("change",!0,!0);b.remove()}).on("click","foreign button",function(){let b=p(this);_ng(b,"author",_Ba._Dh,1,NaN);_Yo(this);this.closest("foreign").remove()}).on("click","triggers > header add",function(){let b=$(this).closest("triggers")[0];0==$("trigger.empty:last-of-type",b).length&&
$("> content",b).append(V())}).on("dblclick","trigger > ctrl del",function(){let b=$(this).closest("triggers")[0],c=$(this).closest("trigger");_sy(c)&&_Pj(600);let d=_Zg(c);b.value.splice(d,1);c.remove();_Yo(b)}).on("change","triggers",function(){$(this).toggleClass("empty",!$("sep:visible",this).length)})},makeCombinSeqContent:w}})();
