'use strict';_Sf.browserAction.onClicked.addListener(()=>{_Mt("brwrAction","trigActId")(a=>{a&&_3s?_Iy(a):_bg()})});_Sf.windows.getLastFocused({populate:!0,windowTypes:_2k},a=>{_Ui=_kd(a,"id");_7h=_at(_kd(a,"tabs",0)||{})});_Sf.tabs.onCreated.addListener(_wp);
function _wp(a){let b=a.id=_at(a);_gd.push(b);_ts[b]=a;a.openerTabId&&(_Ee[b]=a.openerTabId,Object.keys(_Ee).length.in(50,75,100,150,200,300)&&_wt(()=>{for(let c in _Ee)(_Ee[c]=_ci(_ts[c],"openerTabId"))||delete _Ee[c];for(let c in _Ee)c in _ts||delete _Ee[c]}));a.active||_Do(b,a.windowId);_Lt(_iw,b)}
{let a=_1d(400,_X);_Sf.tabs.onRemoved.addListener(b=>{b==_7h&&(_7h=null);_Do(b,0);_gd.remove(b);_Yk.remove(b);delete _It[b];delete _8[b];_up.push({id:b,time:Date.now()/1E3});a();_Lt(_Pk,b);_Ct&&(_ra[b]=_uu(_ts[b]),setTimeout(()=>{delete _ra[b]},3E3))})}function _1e(a,b,c){b=a.indexOf(b);~b&&(a[b]=c)}function _Uo(a,b,c){b in a&&(a[c]=a[b],delete a[b])}let _qg;
_Sf.tabs.onReplaced.addListener((a,b)=>{_Ya(_Vr,[b,a]);_7h==b&&(_7h=a);_1e(_gd,b,a);_1e(_Yk,b,a);_Uo(_ts,b,a);_Uo(_It,b,a);_Uo(_8,b,a);_Uo(_Ee,b,a);for(let [c,d]of _Ee)d==b&&(_Ee[c]=a);for(let [,c]of _0k)_1e(c,b,a);_qg||(_qg={});_qg[b]=a});
{let a=0;_Sf.tabs.onActivated.addListener(({tabId:b,windowId:c})=>{var d=Date.now()-0;_Vj(c,b,d);(d=c==_Ui)&&(_7h=b);c=_pj[c];let e=_ts[b];e||(e=_ts[b]={id:b,windowId:window.id,window:c});const f=_gp(c);_co[b]&&1E3<Date.now()-a&&(delete _co[b],f&&"about:blank"==_uu(e)&&(_Ya(_9p,[_ww,_ww|_Lw,_Uk,_Qp,_Qp|_Lw,_Uk|_Lw,_af,_af|_Lw]),a=Date.now()));const g=_kd(c,"activeTab","id");c.activeTab=e;_qp(b,!d);g!=b&&(_Lt(_oe,g),f&&_Lt(_My,g));setTimeout(()=>{_Lt(_5w,b);f&&_Lt(_Ly,b)},80)})}let _wu;
function _Tg(a,b){_wu&&(3E3>Math.abs(Date.now()-_wu)&&b.startsWith("https://www.google.com/url?q=")&&(b=decodeURIComponent(b.substr(29)),_9j(a,{code:`location.replace(${JSON.stringify(b)}) ; document.body.style.opacity=0`})()),_wu=0)}
{let a={},b;_Sf.tabs.onUpdated.addListener((c,d)=>{let e="loading"==d.status?_ho:"complete"==d.status?_7a:d.discarded?_oo:d.audible?_jr:!1===d.audible?_lh:0;if(e==_oo){if(c==b){b=null;return}b=c}d.url&&(c==_7h&&_6y(d.url),_ng(_ts,c).url=d.url,_wu&&_Tg(c,d.url),_Lt(_Ht,c));if(e){e==_ho&&c in _It&&(_8[c]=Date.now(),_Sf.tabs.getZoom(c,f=>{_Pa(f,2)!=_It[c]&&_la(c,_It[c],!0)}));if(e==_ho){a[c]=setTimeout(()=>{delete a[c];_Lt(e,c)},10);return}if(e==_7a&&a[c]){clearTimeout(a[c]);return}_Lt(e,c)}_Ku&&d.favIconUrl&&
(d=_5h(_uu(_ts[c])),delete _k[d],_8g(d)(_cy));e==_7a&&_ai&&_Ya(_Jt,{tabId:c});e==_7a&&(new URL(_uu(_ts[c]))).hostname==_9t&&_d(c)})}
function _d(a){_9j(a,{code:`(${(function(b){let c=d=>d&&chrome.runtime.sendMessage({[d.value]:decodeURI(d.closest("a").href)});window._ACtlExt||addEventListener("webSettgs",d=>c(d.target));window._ACtlExt=document.querySelector("ACtlExt")||document.head.appendChild(document.createElement("ACtlExt"));window._ACtlExt.setAttribute("ver",b);c(document.querySelector("a [value=redirSttgs]"))})})(${JSON.stringify("2024.6.19")})`})()}_Sf.tabs.onAttached.addListener((a,b)=>{_ng(_ts,a).windowId=b.newWindowId});
_Sf.windows.onFocusChanged.addListener(a=>{_fy[a]||!_pj[a]&&!_Bp[a]||(_Bp[a]&&delete _Bp[a],_3i([a])())});_Sf.windows.onCreated.addListener(_uh);function _uh(a){a.cTime=Date.now();clearTimeout(_0r);_0h.push(a.id);_pj[a.id]=a;a.state.in("normal","maximized")&&(a.prevState=a.state);_3i([a.id])();_Lt(_vk,a.id)}_Sf.windows.onRemoved.addListener(_Jh);function _Gp(a){_0h.remove(a);_jf.remove(a);_lg(a,null);delete _pj[a];a==_Ui&&_Sf.windows.getLastFocused({windowTypes:_2k},b=>_Ui=_pd()?null:b.id)}
function _Jh(a){_Gp(a);_Lt(_yf,a)}_Sf.system.display.onDisplayChanged.addListener(()=>{_je(()=>_Fd())});{let a;_Sf.runtime.onUpdateAvailable.addListener(()=>{_ki(2)&&_hh(2);a=!0});_Sf.idle.onStateChanged.addListener(b=>{"active"!=b&&setTimeout(()=>_Sf.idle.queryState(60,c=>{"active"!=c&&(a?_hh(2):!_9f()&&_Xs&&864E5<Date.now()-_Xs?_hh(1):_to||_Ya(_ul))}),1E3*(15*Math.random()+5)|0)})}if(_Sf.sessions){let a=_Sf.sessions.onChanged;a.addListener(_cy);a.removeListener(_cy)}
_Sf.contextMenus.onClicked.addListener(_ug(function*(a){if("reloadExtn"==a.menuItemId){a=yield _ky(_li);let b=yield _qs(),c={allWinIds:b.map(d=>d.id),idToHndl:_fy,hndlToId:_oj,actionQueue:_h};a&&!a.actWinMine&&(c.focusedId=(b.filter(d=>d.focused)[0]||{}).id,c.lastFocusId=((yield d=>_Sf.windows.getLastFocused({windowTypes:_2k},d))||{}).id,c.focusedId==c.lastFocusId&&(delete c.lastFocusId,_fy[c.focusedId]==a.focusWin&&delete c.focusedId),c.hijackedWins=Object.keys(_Bp));_D("diagnostics",c.add(a));_hh(1,
!0)}else a.menuItemId.startsWith("binSwtch")&&_ae(a.menuItemId,a.checked)}));_Sf.runtime.onInstalled.addListener(_ug(function*(a){if("update"==a.reason&&"2024.6.19"!=a.previousVersion){yield _yw.wait();let b=yield _xt();b.errorCount=yield _gf();_Pf("update",b.add({prevVersion:a.previousVersion}));_vy(a.previousVersion,"2021.4.5")}}));_Sf.runtime.onMessageExternal.addListener((a,b,c)=>{b=_Te.indexOf(b.id);if(0<=b)switch(a){case "TBBtnInit":_hw(b);break;case "TBBtnClick":_Lt(_yu+b),c(!0)}});_2g(_tt);
_sd({customEntities:{},LOCAL:{}},_ug(function*({customEntities:a,LOCAL:b}){_xj(b.localSync);_xk(b.remoteSync);yield c=>_wt(c);yield c=>_je(c);_Xj=b.natHostInstalled;b.installTime?(b.installTime<+new Date(2020,2,1)/1E3&&(b.installTime*=1E3),_Ia=b.installTime,_Hp=Math.floor(_Ia/1E3),_Dh=_e()):(yield _Ca({"LOCAL.installTime":_Ia}),_Pf("install"));_il=b.switchStates||{};_Jo=a;_8i();a=yield _Xf(2);b.installTime||_bg();_Ft();a&&_dh(!0);_Ge({url:`*://${_9t}/*`})(c=>c.forEach(d=>_d(d.id)));_yw.send(a,!0)}));
