'use strict';let _ni={tse:{editor:_fo(),newName:"My custom tab selection",newValue:[],genericName:"tab selection"},gridLayout:{editor:_pp,newName:"My grid",newValue:{},genericName:"grid layout"},menuSpec:{editor:_Aj(),newName:"My custom menu",newValue:{type:"custom",content:[]},genericName:"menu"},menuStyle:{editor:_cy,newName:"My menu style",newValue:{},genericName:"menu style"},binSwtch:{editor:_cy,newName:"My switch",newValue:{},genericName:"switch"},script:{genericName:"script"}};const _3e="Other...";
let _wh={1:"Favorite list One",2:"Favorite list Duo",3:"Favorite list Terna",4:"Favorite list Quater",5:"Favorite list Penta",6:"Favorite list Hex",7:"Favorite list 7",8:"Favorite list Octave",9:"Favorite list Nona",10:"Favorite list X"};function _md(a){let b=0;for(;++b in(_Ba._Jo[a]||{}););return a+":"+b}function _vi(a,b){return(c=_cy)=>{let e=_md(a),d={name:"binSwtch"==a?`${_ni[a].newName} ${Object.keys(_Ba._Jo[a]||[]).length+1}`:"",value:b||_wf(_ni[a].newValue)};_5g(e,d,0,()=>c(e))}}
function _sk(a,b){_Vk(a,c=>{c?_2(`This item is being used in <r>${c}</r> other places. <br> It cannot be deleted.`):_vj(a,b)})}function _vj(a,b){let c=_Yf(a)[0];if("script"==c){let e=_kd(_Np(a),"value","srcFile");e&&_Ba._9i(e)(d=>{_ak(d,void 0)});_8k(a)()}_5g(a,void 0,0,()=>{"menuSpec"==c&&_Pj(0);b&&b()})}
function _2r(a){_sd({trigActList:null,customEntities:{},mouseGest:{}},b=>{const c=JSON.stringify([b.trigActList,b.customEntities.tse,b.customEntities.menuSpec,b.mouseGest.triggers]);a(e=>(c.match(new RegExp('"'+e+'"',"g"))||[]).length)})}function _Vk(a,b){_2r(c=>b(c(a)))}
let _ha=(...a)=>_Ud(a,!0),_Ud=_qf(function*(a=[],b){do{var c=!1;let e=yield f=>_2r(f),d=new _Wa;a.length||(a=Object.keys(_Ba._Jo));for(let f of a)for(let [g,h]of _Ba._Jo[f]||[])if(!b||!h.name||!h.value||"binSwtch"==f){const k=f+":"+g;0==e(k)&&(_vj(k,d.onReady()),!c&&f.in("tse","menuSpec")&&(c=!0))}yield f=>d.setCallback(f)}while(c)});function _sy(a){return!!$(a).find("[entityType=binSwtch][value^=b]")[0]}function _Pj(a=0){setTimeout(()=>_ha("binSwtch")(),a)}
function _nf(a=0){setTimeout(()=>_ha("menuSpec")(),a)}let _yj=_qf(function*(a,b){var c=_Yf(a)[0];let e=_ni[c].genericName;if(b)for(let d of _ea(c)){if(c=_Np(d).name,d!=a&&!_ck(b,c))return _2(`There's already a ${e} called <b>${c}</b>. <br> Please enter a different name.`,{type:"warning"}),[!1]}else if((b=_Np(a).name)&&1<(yield d=>_Vk(a,d)))return _2(`This ${e} is being used in more than one place. <br> Its name cannot be blank.`,{type:"warning"}),[!1,b];return[!0]});
function _be(a){var b=_Yf(a)[0];let c=_wf(_Np(a,b)),e=_ni[b].genericName,d=$(`\n <namedEntityEditor DataModule>\n <div>\n <input type=text spellcheck=false maxlength=80 placeholder="Give a name to this ${e} (optional)" title="Click to change name">\n <h h=/entName ent="${e}"></h>\n </div>\n </namedEntityEditor>\n `).prop("value",c.value).on("change",function(){_5g([a,"value"],this.value,100,()=>{$(`[value='${a}']`).triggerEvt("redefine",!0)})}).on("close",function(){$(this.children).triggerEvt("close")}).find("input").val(c.name).on("input",
_F(250,_ug(function*(){let f=this.value.trim(),[g,h]=yield _yj(a,f);h&&(this.value=h);if(!g)return!1;_5g([a,"name"],f);$(`[value='${a}'] > l`).text(f||_3e);$(this).closest("floatbox").triggerEvt("resize")}))).change(!1).end();d.updateEmptyState=function(){this.toggleClass("empty",$("> .empty",this)[0])};b=_ni[b].editor(d[0]).on("change",()=>d.updateEmptyState());d.append(b).prop("onInitDone",b[0].onInitDone).updateEmptyState();return d}
function _dr(a,b){return _aw(a,b,"brlt RR,HR","tailAndShadowBlurry","auto-detect","transformAndOpacitySlow")}function _5f(a,b){return _Ws("binSwtch",a,b,"",!1,!0,!1,"",!1)}
function _Ws(a,b,c,e,d=!1,f=!0,g=!0,h="",k=!0){let l=_Np(c,a);e=e||`Choose a ${_ni[a].genericName}...`;d&&"boolean"==typeof d&&(d="(blank)");return`<customSelect entityType=${a} name="${b}" value="${c||""}" ${f?"newOpt":""} ${d?`emptyOpt="${d}"`:""} ${g?"editBtn":""} ${k?"":"noDelBtn"} optionsFilter="${h}" placeholder="${e}">${_Tp(c)?`<l>${l.name||_3e}</l>`+(g?" <edit></edit>":""):l.name||""}</customSelect>`}
function _3k(a,b,c){let e=b instanceof HTMLElement,d=e?$(b).attr("value"):b,f="binSwtch"==$(a).attr("entityType");c=(f?"":c)||(e?$("l",b).text()||$(b).text():_Np(d,$(a).attr("entityType")).name||"");let g=$(a).attr("value");if(_Tp(g)){let h=_Np(g);h.name&&!f||_Vk(g,k=>{1>=k?(_vj(g),a.prevAnonEntity=h.value):f||(a.prevAnonEntity=g)})}$(a).attr("value",d).html(_Tp(d)?`<l>${c}</l>`+($(a).is("[editBtn]")?"<edit></edit>":""):`${c}`).triggerEvt("change",!0)}
function _ya(a,b,c,e){let d=_Np(b,a),f=_Tp(b);return`<item value="${b}" ${f?"custom":""} ${d.perms?`perms="${d.perms}"`:""} ${b==c?"selected":""}>\n <l>${d.name}</l> ${d.help?`<h h="/${a}/${d.help}"></h>`:""} ${f&&!e?'<del button title="Delete"></del>':""}\n </item>`}
function _r(a){var b=$(a).attr("value");let c=$(a).attr("entityType"),e=$(a).attr("emptyOpt"),d=$(a).attr("optionsFilter"),f=$(a).is("[newOpt]"),g=$(a).is("[noDelBtn]"),h="",k="";for(let [l,m]of _Ba._tt[c])if(!d||d in m)h+=_ya(c,l,b,g);for(let l of _ea(c,!0))k+=_ya(c,l,b,g);b=$(`\n <namedEntityMenu DataModule>\n ${e?`<item value="" label="${e}"></item>`:""}\n ${h}\n ${h&&k?"<hr>":""}\n ${k}\n ${f?`\n <hr>\n <newEntity type=${c}>New ${_ni[c].genericName}...</newEntity>\n `:""}\n </namedEntityMenu>\n `);
return _Oj(b,a)}function _w(...a){return _Ws(...a)}
function _Oj(a,b){return $(a).on("click","item",function(){$(this).triggerEvt("focusLost",!0);_3k(b,this)}).on("click","newEntity",_ug(function*(){var c=$(b).attr("value");if(!_Tp(c)||_Np(c).name)c=b.prevAnonEntity,c="string"==typeof c?c:yield _vi($(this).attr("type"),c),_3k(b,c,_3e);$(this).triggerEvt("focusLost",!0);setTimeout(()=>$("edit",b).triggerEvt("mousedown"),200)})).on("click","del",function(c){c.stopImmediatePropagation()}).on("dblclick","del",function(c){c=$(this).closest("item").attr("value");
_sk(c,()=>$(this).closest("item").remove())})}function _Qi(a,b){let c={};for(let e of a)a=_Np(e,b),c[e]=[a.name,a.help?"/"+b+"/"+a.help:""];return c};
