'use strict';let _h,_Dt,_U,_Nk=!0;var _bd=_qf(function*(a=!1){if(a||_Nk)yield b=>_wt(b),_Py(),_Nk=!1});function _Py(){_gy=_Rt=_yr=_7i=_gt=null;_g={}}
let _Ua=_ug(function*(a=0,b=!1){const c=_h[0];yield _Fy(a);if(c==_h[0]){if(b)if("runScript"==_U){if(a=yield g=>_by(g),_Pf("stuckAction",{action:"runScript",answer:a}),c==_h[0]&&(_h.length=1,!a))return}else _Pf("stuckAction",{action:_U});_h.shift();_Iy()}}),_Iy=_ug(function*(a,b=null){if(a)a:if(_h.push([a,b]),1<_h.length){b=4;if("sendInput"==_U){a=_kd(_3s,a,0,"sequence",0)||{};if("stopSendInput"==a.action){_z([],_cy,a.params||{});_h.shift();break a}b=8}else"wait"==_U&&(b=30);_h.length==b&&_Ua(1200,
!0);return}for(_Nk=!0;_h.length;){const c=_h[0];[a,b]=c;(a=_3s[a])&&(yield _dk(a,null,b));if(c!=_h[0])break;_h.shift()}}),_Wu=0;
var _dk=_qf(function*(a,b,c){c||(c=_fk());let g=0;a:for(let h of a){yield _bd();if(g++||!b)_qg=null,b=h.targets?yield _xd(c,_zk,h.targets):_7h?[[_7h]]:[];b:for(let {action:f,params:k}of h.sequence||[]){yield _bd();let l=_3p(f,k);if("object"==typeof l)b=yield _dk(l,null,c);else{_U=f;_qg&&(b.forEach(d=>{for(let e=0;e<d.length;++e)_qg[d[e]]&&(d[e]=_qg[d[e]])}),_qg=null);try{let d=yield e=>l(b,e,k||{},c);if(!_0p(d)){if("inner"==d.break)break b;if("outer"==d.break)break a}b=d}catch(d){_Pf("error",{action:f,
stack:d.stack,params:"saveUrl"==f?k:void 0})}_Nk=!0}}}return b});
_tt.action={activateTabs:{name:"Activate tabs",grp:"tab",h:1,value:_Ys},reloadTabs:{name:"Reload tabs",grp:"tab",value:_Ow},goBackTabs:{name:"Go back",grp:"tab",value:_vo},goForwardTabs:{name:"Go forward",grp:"tab",value:_7w},goUpURL:{name:"Go upper URL",grp:"tab",h:1,value:_Hw},loadUrls:{name:"Open URL",grp:"tab",h:1,value:_Zt},highlightTabs:{name:"Select tabs",grp:"tab",h:1,value:_1o},pinTabs:{name:"Pin tabs",grp:"tab",value:_Pu},zoomTabs:{name:"Zoom tabs",grp:"tab",value:_oa},muteTabs:{name:"Mute tabs",
grp:"tab",h:1,value:_Lg},moveTabs:{name:"Move tabs",grp:"tab",h:1,value:_ey},detachTabs:{name:"Detach tabs",grp:"tab",h:1,value:_wr},groupTabs:{name:"Group tabs",grp:"tab",h:1,value:_Ep},duplicateTabs:{name:"Duplicate tabs",grp:"tab",h:1,value:_3u},openInIncognito:{name:"Open in incognito",grp:"tab",h:1,value:_gw},closeTabs:{name:"Close tabs",grp:"tab",h:1,value:_2y},undoClose:{name:"Reopen tabs",grp:"tab",h:1,value:_Yw,perms:"ses"},unloadTabs:{name:"Unload tabs",grp:"tab",h:1,value:_zj},favoriteTabs:{name:"Favorite tabs",
grp:"tab",h:1,value:_Si},alterTgtTabs:{name:"Alter target tabs",grp:"",value:_we},focusWin:{name:"Focus",grp:"win",h:1,value:_Md},moveResizeWins:{name:"Move/Resize",grp:"win",h:1,value:_Ma},fitWinsToGrid:{name:"Fit to grid",grp:"win",h:1,value:_Ma},tileWins:{name:"Tile",grp:"win",h:1,value:_hp},minimizeWins:{name:"Minimize",grp:"win",value:_0d(_Yt)},maximizeWins:{name:"Maximize",grp:"win",value:_0d(_pf)},restoreWins:{name:"Restore",grp:"win",h:1,value:_ko},fullscreenWins:{name:"Fullscreen",grp:"win",
value:_Ig},hideWins:{name:"Hide",grp:"win",h:1,value:_To},scrollWins:{name:"Scroll",grp:"win",h:1,value:_2a},topmostWins:{name:"Stay on top",grp:"win",h:1,value:_0d(_qk)},sendWinsToBottom:{name:"Send to bottom",grp:"win",h:1,value:_De},openBookmarks:{name:"Open bookmarks",grp:"bmrk",h:1,value:_Zt,perms:"bkm"},bookmarkTabs:{name:"Bookmark tabs",grp:"bmrk",h:1,value:_ca,perms:"bkm"},bookmarkUrls:{name:"Bookmark URL",grp:"bmrk",h:1,value:_ca,perms:"bkm"},openMenu:{name:"Open menu",grp:"menu",h:1,value:_Vi},
closeMenu:{name:"Close menu",grp:"menu",value:_2d},moveSelectMark:{name:"Move item mark",grp:"menu",h:1,value:_Nj},selectMarkedItem:{name:"Select menu item",grp:"menu",h:1,value:_wj},clpbrdCut:{name:"Clipbrd cut",grp:"clbrd",h:1,value:_rr(_ej)},clpbrdCopy:{name:"Clipbrd copy",grp:"clbrd",h:1,value:_rr(_Dj)},clpbrdPaste:{name:"Clipbrd paste",grp:"clbrd",h:1,value:_rr(_lk)},clpbrdPut:{name:"Clipbrd put",grp:"clbrd",h:1,value:_Ru()},copyElemUrl:{name:"Copy hovered URL",grp:"clbrd",h:1,value:_Pr,perms:"hst"},
copyLinks:{name:"Copy selected URLs",grp:"clbrd",h:1,value:_Lf},extractURLs:{name:"Extract URLs",grp:"clbrd",h:1,value:_Li},txtToUrl:{name:"Text to URL",grp:"clbrd",h:1,value:_xa},delDupLines:{name:"Erase dup. lines",grp:"clbrd",h:1,value:_dw},clpbrdDiscard:{name:"Discard",grp:"",h:1,value:_cy},setVolume:{name:"Change volume",grp:"sys",h:1,value:_Mf},showDesktop:{name:"Show desktop",grp:"sys",h:1,value:_Ug},setMonBright:{name:"Screen brightness",grp:"sys",h:1,value:_Gd},screenSaver:{name:"Screen saver",
grp:"sys",h:1,value:_Uy("scrSvr")},setMonPower:{name:"Turn off screen",grp:"sys",h:1,value:_Uy("monOff")},brkActSeq:{name:"Continue chain if",grp:"exec",h:1,value:_Lp},setSwtchSt:{name:"Set switch state",grp:"exec",h:1,value:_Sa},wait:{name:"Wait",grp:"exec",h:1,value:_So},saveUrl:{name:"Save URL",grp:"other",h:1,value:_Dk},playAudio:{name:"Play audio",grp:"other",h:1,value:_Kt},insertText:{name:"Insert text",grp:"other",h:1,value:_Ru(!0)},sendInput:{name:"Synthesize input",grp:"other",h:1,value:_ld},
stopSendInput:{name:"Stop synth input",grp:"other",h:1,value:_z},runCommand:{name:"Open file/program",grp:"other",h:1,value:_os},runScript:{name:"Run script",grp:"other",h:1,value:_fd,perms:"hst"},screenShot:{name:"Take screenshot",grp:"",h:1,value:_cy},openNTP:{name:"Open new tab",h:1,value:{gener:_6t}},goBack:{name:"Back",h:1,value:[{sequence:[{action:"goBackTabs"}],targets:"currentTab"}]},goForward:{name:"Forward",h:1,value:[{sequence:[{action:"goForwardTabs"}],targets:"currentTab"}]},reload:{name:"Reload",
h:1,value:[{sequence:[{action:"reloadTabs"}],targets:"currentTab"}]},zoomIn:{name:"Zoom in",h:1,value:[{sequence:[{action:"zoomTabs",params:{type:1,steps:1}}],targets:"currentTab"}]},zoomOut:{name:"Zoom out",h:1,value:[{sequence:[{action:"zoomTabs",params:{type:-1,steps:1}}],targets:"currentTab"}]},duplicate:{name:"Duplicate tab",h:1,value:[{sequence:[{action:"duplicateTabs"}],targets:"currentTab"}]},detach:{name:"Detach tab",h:1,value:[{sequence:[{action:"detachTabs"}],targets:"currentTab"}]},switchPrev:{name:"Switch to previous tab",
h:1,value:[{sequence:[{action:"activateTabs"}],targets:"prevUsedTab"}]},switchLeft:{name:"Switch to left tab",value:[{sequence:[{action:"activateTabs"}],targets:"leftTabWrap"}]},switchRight:{name:"Switch to right tab",value:[{sequence:[{action:"activateTabs"}],targets:"rightTabWrap"}]},switchLeftmost:{name:"Switch to leftmost tab",value:[{sequence:[{action:"activateTabs"}],targets:"firstTab"}]},switchRightmost:{name:"Switch to rightmost tab",value:[{sequence:[{action:"activateTabs"}],targets:"lastTab"}]},
pin:{name:"Pin tab",h:1,value:[{sequence:[{action:"pinTabs",params:{mode:_Fa}}],targets:"currentTab"}]},mute:{name:"Mute tab",h:1,value:[{sequence:[{action:"muteTabs",params:{mode:_Fa}}],targets:"currentTab"}]},close:{name:"Close tab",h:1,value:{gener:_bj}},closeLefts:{name:"Close left tabs",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"allLeftTabs"}]},closeRights:{name:"Close right tabs",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"allRightTabs"}]},closeOther:{name:"Close other tabs",
h:1,value:[{sequence:[{action:"closeTabs"}],targets:"otherTabs"}]},closeWin:{name:"Close window",h:1,value:[{sequence:[{action:"closeTabs"}],targets:"currWinTabs"}]},reopen:{name:"Reopen closed tab",h:1,value:[{sequence:[{action:"undoClose"}]}],perms:"ses"},openElemUrl:{name:"Open element URL",h:1,value:{gener:_1f},perms:"hst"},saveElemUrl:{name:"Save element URL",h:1,value:{gener:_sp},perms:"hst"}};
