'use strict';var _4;function _Bu(a,b=!1){if(b){let c=_pj[_ts[a].windowId];_Ur(c.id,!0,f=>{Object.assign(c,f);f=c.tabs.map(e=>e.id);if(1<f.length){_Yk.remove(a);let e=0;for(let d=0;d<_Yk.length;++d)if(0<=f.indexOf(_Yk[d])&&++e==f.length-1){_Yk.splice(d+1,0,a);break}}})}else _Yk.remove(a),_Yk.push(a)}let _Uu={};function _qp(a,b=!1){1==_Uu[a]?_Uu[a]=2:(delete _Uu[a],a!=_Yk[_Yk.length-1]&&_Bu(a,b))}
function _ls(a,b,c=!1){let f=b.filter(e=>-1!=a.indexOf(e));if(f.length<a.length)f[c?"unshift":"push"](...a.filter(e=>-1==f.indexOf(e)));return f}
function _wt(a){_qs(!0)(b=>{_wl=[];_ts={};let c=_pj;_pj={};let f=[];for(let e of b)b=e.id,delete (_pj[b]=Object.assign(c[b]||{},e)).monitorId,f.push(b);_0h=_ls(f,_0h,!0);_ou=_ls(f,_ou);for(let e of _0h)for(let d of _pj[e].tabs)d.id=_at(d),d.window=_pj[e],d.active&&(d.window.activeTab=d,e==_Ui&&(_7h=d.id)),_ts[d.id]=d,_wl.push(d.id);_gd=_ls(_wl,_gd,!0);a&&a()})}function _lg(a,b){b?(_oj[b]=+a,_fy[a]=+b):(b=_fy[a]|0,delete _oj[b],delete _fy[a],_Ya(_kr,[b]))}
function _zo(a,b,c,f){_Ya(_Tw,{tabId:a,win:_fy[b],time:c,popup:f})}function _Do(a,b){_Ya(_dp,{tabId:a,win:_fy[b]})}let _Vd,_8u;function _6y(a){_8u&&a!=_Vd&&_Ya(_Aw,_Vd=a)}const _vs=parseInt(_np.substr(13,2),36);let _ow,_Hf,_oi=0;
function _yi(a,b){a+=_vs;if(a!=_oi){var c=_oj[_oi];c&&_Gh(c,e=>{e&&(_Hf&&_Hf.send(),_ng(_pj,c).focused=!1,_Lt(_ed,c),_Lt(_My,e.id))});var f=_oj[a];_oi=f?a:0;f?(_Of=!0,_Gh(f,e=>{e&&(_Ui=f,_7h=e.id,_ng(_pj,_Ui).focused=!0,_qp(_7h),_6y(_uu(e)),_ow&&_ow.send(),b||(_Lt(_te,_Ui),_Lt(_Ly,_7h)))})):a&&_Sf.windows.getAll({populate:!0,windowTypes:["devtools"]},e=>{for(let d of e)~_0h.indexOf(d.id)||(_uh(d),_wp(d.tabs[0]))})}}
function _4g(a,b){if(0<b&&a.length>b){const c=a.charCodeAt(b-1);a=a.slice(0,b-(55296<=c&&56319>=c?1:0))}return a}function _Gh(a,b){_Ge({windowId:a,active:!0})(c=>{c&&c[0]?(c[0].id=_at(c[0]),b(c[0])):_Vy(a,b)})}function _Vy(a,b){_Ur(a,!0,c=>{if(_pd()||!c||!c.tabs)return b();for(let f of c.tabs)if(f.active)return f.id=_at(f),b(f)})}
{let a={};var _Vj=function(b,c,f){!a[b]&&_fy[b]&&(_zo(0,b,f),b==_Ui&&_6y(_uu(_ts[c])));clearTimeout(a[b]);a[b]=setTimeout(()=>{let e=a[b];_Sf.tabs.get(c,d=>{if(!_pd()){if(e!=a[b])return;_fy[b]&&_zo(c,b);b==_Ui&&_6y(_uu(d))}delete a[b]})},300)}}let _Of=!0,_0r;
function _Za(a){_Of=!1;_ou=[];for(let b of a)(a=_oj[b])&&_ou.push(a);clearTimeout(_0r);_ou.length!=_0h.length&&_qs()(b=>{b=b.map(c=>c.id);_0w(_0h,b).forEach(_Jh);_0h.length!=_ou.length&&(_0r=setTimeout(()=>{let c=_0w(_0h,_ou);c.length&&_wd(c)},2E3))})}function _wd(a){a.forEach(b=>_lg(b,void 0));_3i(a)(()=>{let b=_0h.length;if(Object.keys(_oj).length!=b||Object.keys(_fy).length!=b)_fy={},_oj={},_Ya(_kr),_3i()(()=>{})})}function _Dw(a,b,c){return"app"==c?a.endsWith(b):a.startsWith(b)}
function _Xa(a){for(let b of a||_0h)if(_fy[b])for(let c of _kd(_pj,b,"tabs")||[])c.active?_zo(c.id,b,void 0,"popup"==_pj[b].type):_Do(c.id,b)}let _3i=a=>b=>{_Xy(a)(c=>{_Xa(c);b&&b()})};
{let a=[];var _Xy=d=>k=>{a.push([d||_0h,k]);1==a.length&&_mt(function*(){for(;a.length;){let [l,r]=a[0],t=yield c(l);Promise.resolve().then(()=>r(t));a.shift()}})};let b=[],c=_qf(function*(d){var k=Date.now();d=d.filter(r=>!_fy[r]);if(_Bh&&d.length){let r=(g,m)=>{q.remove(g);w.remove(m);if(u[m].parentHwnd){if(!_Bp[g]){_Bp[g]=!0;let h=_pj[g].activeTab;_Gp(g);_Pf("hijackedWin",u[m].sc().add({id:h.id,url:_uu(h),title:h.title}))}}else _lg(g,m)},t=()=>{let g=u.sc().keep(...w),m={};for(let h of q){let n=
e(h,g),p=!1;for(let v of n)m[v]&&(delete m[v],p=!0);1!=n.length||p||(m[n[0]]=h)}for(let [h,n]of m)r(n,+h)},x=(g,m,h,n)=>{for(let p of g)if(0<=q.indexOf(p.id))for(let v of m)if(p.id==v.id){g=v.left-p.left;let B=v.top-p.top;if((h?(y=>0<y&&3>y)(g/h):g==h)&&(h?(y=>0<y&&3>y)(B/n):B==n))return p.id;break}},C=_qf(function*(){[u]=yield _eg(_ky(_Ka,{refWin:Object.keys(_oj)[0]|0,inclHjkd:z}),g=>_wt(g));(A[z|0]=u)&&(w=Object.keys(u).map(g=>+g).filter(g=>!_oj[g]))}),u,A=[],w,q,z;q=d.slice();a:{for(;;){yield C();
if(!u)break a;for(let g=0,m=!0;8>g&&q.length&&w.length;++g)if(m?m=!1:yield C(),t(),q.length){const h=(g%2*2-1)*(g>>1&1)*((g>>2)+1),n=(g%2*2-1)*(g+2>>1&1)*((g>>2)+1);for(let [,p]of _Ki(w)){var l=yield _qs();yield _ky(_si,{win:p,x:h,y:n,noNotif:!0});let v=yield _qs();yield _ky(_si,{win:p,x:-h,y:-n});(l=x(l,v,h,n))&&r(l,p)}}if(!z&&q.length)z=!0;else break}_Yi(u);if(q.length&&_0w(q,b).length){k=Date.now()-k;let [g,m]=yield _eg(_ky(_Ve),_qs(!0));m.forEach(h=>{(h.tabs=h.tabs.filter(p=>p.active)).forEach(p=>
p.keep("active","title","url","pendingUrl","width","height"));let n=_kd(_pj[h.id],"cTime");n&&(h.age=(Date.now()-n)/1E3)});(()=>{for(let h of q)for(let n of m)if(n.id==h){if(n.tabs[0])return!0;break}})()&&(k=_wf({ID_HWND:_fy,HWND_ID:_oj,missingIds:q,unusedHwnds:w,data:f({winsData:m,hwndData:A[0],hjkdHwnd:A[1],allHwndData:g}),time:k}),_Pf("missingHwnds",k),q.forEach(h=>b.add(h)))}}}return d}),f=d=>{d=_Bt(JSON.stringify(d),"UTF-8",!1);let k="";for(let l=d.length;0<l--;)k+=String.fromCharCode((d.charCodeAt(l)+
(1.3*(l+d.length)|0))%256);return btoa(k)},e=function(d,k){let l=_pj[d];d=[];if(l){for(let [t,x]of k)x.state==l.state&&_Yp(l,x.coords)&&d.push(+t);let r=_kd(l,"activeTab","title");if(1<d.length&&r&&d.every(t=>k[t].title)){r=r.substr(0,200);let t=d.filter(x=>_Dw(k[x].title,r,l.type));0<t.length&&(d=t)}}return d}}function _Yi(a){if(a)for(let [b,c]of a)(a=_oj[b])&&(c.visible?_jf.remove(a):_jf.add(a))}
let _Ad=_Eh(),_X=_ug(function*(){const a=_Sf.sessions;let b=_up;_up=[];let c=a&&a.getRecentlyClosed&&(yield e=>a.getRecentlyClosed({maxResults:Math.min(b.length,a.MAX_SESSION_RESULTS)},e))||[],f={};for(let e of b){let d=_kd(_ts,e.id,"url");if(d)a:for(let k of c){if(1.5<e.time-k.lastModified)break;for(let l of k.tab?[k.tab]:k.window.tabs)if(d==l.url){_Yu&&(f[e.id]=+l.sessionId);k.tab&&(_Ad.length>=a.MAX_SESSION_RESULTS&&_Ad.delPos(0),_Ad[l.sessionId]=_ts[e.id].windowId);break a}}f[e.id]+=0}_Ya(_xw,
f)});
