'use strict';let _Et=0;function _9f(){return _Et||"undefined"!=typeof _Ra&&!_7p(_Ra)}function _fd(b,f,g,l){let m=g.bkgrnd?[0]:_Ga(b);++_Et;_Oo(g.scriptId,m,b,l)(e=>{--_Et;g.async||f(e)});g.async&&f(b)}
let _Oo=_qf(function*(b,f,g,l){let m=yield _Qw(b);if(m){b=yield _mk(b,f,g,m,void 0,l,!0);f=!1;l=[];for(let e of b)if(e)if(e===(e|0)&&(e=[e]),_0p(e))f=!0,l.push(...e.map(n=>_0p(n)?_ag(n):_ts[n]?n:null).filter(n=>n));else if("object"==typeof e&&"string"==typeof e.break&&1==Object.keys(e).length)return e;if(f)return l}return g}),_mk=_qf(function*(b,f,g,l,m,e,n,r){let a=[];for(let c of f)0<=c&&a.push(_Mr(b,c,g,l,m,e,n,r));return yield Promise.all(a)}),_Ji;
{var _Mr=function(a,c,d,h,p,k,t,u){return new Promise((v,w)=>{_Hi(c,{scriptId:a,tabId:c,targetTabs:d,funcCode:p?h+"":`${55>_Zo?"":"async"}()=>{\n${h}\n}`,args:_3g(p),trigInstId:k,frmFlt:u})(q=>{q=q||{};!t&&"error"in q?w(q.error):v(q.result)})})},_Hi=(a,c)=>(d=_cy)=>{+a?c.frmFlt?r(+a,c,d):n(+a,c,d):e(c,d)};window.addEventListener("message",a=>m(a.data,{id:0},c=>a.source.postMessage({result:c,pongId:a.data.pingId},"*")));_Sf.runtime.onMessage.addListener((a,c,d)=>{m(a,c.tab,d);return!0});let b={},f=
a=>{for(var c=1;c in b;++c);b[c]=a;return c};const g=a=>_Sf.runtime.getURL(_ce)+"?file="+encodeURIComponent(a),l=_F(-700,a=>_rs()(c=>_dy(c)._Na(a)));let m=function(a,c,d){if(a.pongId)b[a.pongId]&&"dontDel"!=b[a.pongId](a.result)&&delete b[a.pongId];else if(c&&"userAPI"==a.type){++_Et;let h=()=>_Ji(a,c)((...p)=>{--_Et;d(...p)});_Ji?h():_kw("/file91.js",h)}else a.imprtSttgs?l(a.imprtSttgs):a.viewSttgs?_Sf.tabs.create({active:!0,url:g(a.viewSttgs)}):a.redirSttgs&&_Sf.tabs.update(c.id,{url:g(a.redirSttgs)})},
e=_ug(function*(a,c){let d=document.getElementById("BGScript");d||(d=_3r('<iframe id=BGScript src="file2.html">').children[0],yield h=>{d.onload=h;document.body.appendChild(d)});a.pingId=f(c);d.contentWindow.postMessage(a,"*")}),n=_ug(function*(a,c,d){for(let p=0;;++p){var h=yield k=>_Sf.tabs.sendMessage(a,c,{frameId:0},k);_pd("msgToIsolCtx");if(void 0!==h||0<p||c.event)break;try{yield _9j(a,{file:"file33.js"})}catch(k){return d({error:k})}}d(h)}),r=_ug(function*(a,c,d){try{let h=
yield _9j(a,{allFrames:!0,matchAboutBlank:!0,code:"!!window.FN"});h.filter(k=>!k).length&&(h=yield _9j(a,{allFrames:!0,matchAboutBlank:!0,file:"file33.js"}));let p=h.length;h=[];c.frmCBId=f(k=>{if(k){if("error"in k)return d(k);h.push(k.result)}if(--p)return"dontDel";d({result:h})});yield k=>_Sf.tabs.sendMessage(a,c,k);_pd()}catch(h){return d({error:h})}})}let _Qw=_qf(function*(b){(b=_Np(b,"script").value)&&b.srcFile&&(b=yield _Nw(b.srcFile,!0));return b?b.srcCode:""});
var _Nw=_qf(function*(b,f){b=yield _9i(b);let g=_ak(b);if(_Hy(b)||!_9u(b)){f=yield _tj(b,"text",_kd(g,"ldTime")||0);if(f.error)return{error:f.error};if(null!=f.content)return _ak(b,{srcCode:f.content,encode:f.charEnc,ldTime:Date.now()})}else if(!g||6E4<Date.now()-g.checkTime){let l=_qf(function*(){let [m,e]=yield _Pw(_c(b,"text",void 0,void 0,{"If-Modified-Since":(new Date(_kd(g,"ldTime")||0)).toUTCString()}));return 200==e.status?_ak(b,{srcCode:m,ldTime:Date.now(),checkTime:Date.now()}):304==e.status?
_ak(b,g.add({checkTime:Date.now()})):{error:e.status}});if(f&&g)l()();else return yield l()}return g});
_tt.script={saveAllImg:{name:"Example 1: Download all images",help:"",value:{srcCode:"let count = 0 ;\n//for each image in the page\nfor(let image of document.images){\n\t//if the image is bigger than 100x100 pixels\n\tif( image.src && image.width > 100 && image.height > 100 ){\n\t\t//save it to the desktop under a folder named after the page's domain\n\t\tlet filepath = await ACtl.saveURL(image.src, `<desktop>/${location.hostname}/`) ;\n\t\tconsole.log(++count, image.src, ' --\x3e ', filepath) ;\n\t}\n}\nalert(count + ' IMAGES SAVED.') ;"}},captTabPub:{name:"Example 2: Take page screenshot and upload it",
help:"",value:{srcCode:"//Take a shot of the current tab\nlet [[, dataUri]] = await ACtl.captureTab('#currentTab') ;\n//Put the image in the clipboard\nawait ACtl.setClipboard({image: dataUri}) ;\n//Open http://snag.gy in a new tab\nlet [tabId] = await ACtl.openURL('http://snag.gy', {rightOf: '#currentTab'}) ;\n//Wait for the tab to finish loading\nawait ACtl.on('tabLoadEnd', tabId) ;\n//Activate the new tab and focus its window\nawait ACtl.setTabState(tabId, 'active focused') ;\n//Execute AutoControl's [CLIPBRD PASTE] action\nawait ACtl.execAction('#clpbrdPaste') ;"}}};
