'use strict';const _Tt=document.currentScript.parentElement;function _2(c,a={},h=_cy){let k=_Ze("basicForm",{},_Tt).addClass(a.type||"info").addClass(!1===a.btn?"noBtn":"").append(_Ze("messageForm",{},_Tt));k.find("msg").css("maxWidth",a.width||"").append(c);k.find("button").click(function(){_H(this);h()});return _6k(a.title||"",k,"noClose",a.nearMouse,!0)}
function _Dg(c,a,h={}){return k=>{var l=_Ze("confirmForm",{},_Tt).addClass(h.icon||"confirm");l.find("msg").css("maxWidth",h.width||"").append(a);let q=l.find("button[accept]").html(h.yes||"Yes")[0];l.find("button[cancel]").html(h.no||"No");$("button",l).click(function(){k($(this).is("[accept]"),_Me($(this).closest("form")[0]))||_H(this)});h.enterOk&&l.keydown(f=>{13==f.keyCode&&q.click()});return _6k(c,l,"noClose",h.nearMouse,!0)}}
function _Wg(c,a={}){return h=>{c=_Ze("basicForm",{},_Tt).addClass(a.icon||"confirm").append(c).on("click","button[value]",function(){let k=this.value;_H(this);h(k)}).find("msg").css("maxWidth",a.width||"").end();return _6k(a.title,c,"",a.nearMouse,null==a.modal?!0:a.modal)}}function _H(c,a=!0){$(c).closest("dialog").triggerEvt({close:a})}function _6k(c,a,h="",k=!0,l=!1){return _Ef(c,a,h,k).Show(l)}
{let c=[];var _Rs=function(a,h){a=[a,h,new _qy,new _qy];c.push(a);1==c.length&&_mt(function*(){for(;c.length;){let k=_2(c[0][0],{type:"success",btn:!1});c[0][2].send("",!0);yield _Fy(c[0][1]);_H(k);c[0][3].send("",!0);c.shift()}});return{onShow:a[2].wait(),onHide:a[3].wait()}}}
function _Ef(c,a,h,k,l,q){const f=_Ze(l?"dialog2":"dialog",{},_Tt).appendTo("body").addClass(h).submit(!1).on("click","button",d=>d.preventDefault()).on("close",function(d,m){if(!d.originalEvent.defaultPrevented||m)this.remove(),_Ag()}).on("dialogOpen focusGained focusLost",function(d,m){var p=$(this).hasClass("active"),n="focusLost"==d.type;"dialogOpen"==d.type&&_Qa(this);(n=p&&n||!p&&!n)&&$(this).toggleClass("active",!p);(n||"focusGained"==d.type&&"force"==m)&&$("> content > *",this).triggerEvt(d.type)}).on("layoutChange",
function(d){$("> content > *",this).triggerEvt(d.type+($(this).hasClass("active")?" layoutRefresh":""))});if(l)f.on("mousedown","> row > [d]",function(d){d.preventDefault();if(!f.is(".maximized")){$(document.body).css("pointer-events","none").parent().css("cursor",$(this).css("cursor"));var m=d.clientX,p=d.clientY,n=f[0].getBoundingClientRect();d={t(b,e,g){b.top+=g;t=!0},l(b,e,g){b.left+=e;u=!0},r(b,e,g){b.right+=e},b(b,e,g){b.bottom+=g},tl(b,e,g){this.t(b,e,g);this.l(b,e,g)},tr(b,e,g){this.t(b,e,
g);this.r(b,e,g)},bl(b,e,g){this.b(b,e,g);this.l(b,e,g)},br(b,e,g){this.b(b,e,g);this.r(b,e,g)}};var r=d[$(this).attr("d")].bind(d),t,u;$(document).on("mousemove.diagRedim",b=>{const e=n.sc();t=u=!1;r(e,b.clientX-m,b.clientY-p);f.css({width:Math.max(0,e.right-e.left),height:Math.max(0,e.bottom-e.top)});u&&f.css("left",e.right-f[0].offsetWidth);t&&f.css("top",e.bottom-f[0].offsetHeight)}).on("mouseup.diagRedim",function(){$(this).off(".diagRedim");$(document.body).css("pointer-events","")})}});c?($("header l",
f).html(c),$("header b",f).click(function(){_H(this,!1)}),$("header",f).mousedown(function(d){d.preventDefault();var m=$(this).closest("dialog");if(!m.is(".maximized")&&!d.target.closest("ctrls")){$(document.body).css("pointer-events","none").parent().css("cursor",$(this).css("cursor"));var p=d.clientX-m[0].offsetLeft,n=d.clientY-m[0].offsetTop;$(document).on("mousemove.dialogDrag",function(r){m.css({top:r.clientY-n,left:r.clientX-p})}).on("mouseup.dialogDrag",function(){$(this).off(".dialogDrag");
$(document.body).css("pointer-events","")})}})):$("header",f).addClass("hidden");$("content",f).append(a);f[0].Show=function(d){$(this).addClass("beforePopup1 transformAndOpacityBounceFast");$(this).attr("modal",!!d);this[d?"showModal":"show"]();$(this).triggerEvt("dialogOpen").removeClass("beforePopup1");return this};q&&f.css({width:q[0],height:q[1]});return _Ed(f).css(_9w(f,k))[0]}
function _1w(c=!0){c?$("busySign")[0]||_Ze("busySign",{},_Tt).addClass("float").appendTo("body"):$("busySign.float").remove()};
