'use strict';var _Sr;
{let l,k={};var _Ya=function(a,b=null,c=null,g=0){let m=a.in(_uf,_Cu,_G);b={type:a,content:b};if(c){var e=2130706431*Math.random()|0;_ng(b,...m?["content"]:[]).callback=e+l}try{return d.postMessage(b),c&&(k[e]=c,g&&setTimeout(()=>q(e,_2p),g)),a==_J&&_Th(void 0),!0}catch(h){return c&&setTimeout(c),!1}},_ky=(a,b,c)=>g=>_Ya(a,b,g,c);let q=function(a,b){let c=k[a];c&&(delete k[a],c(b))},w=function(){for(let a in k)q(a,"")},E=(()=>{function a(e,h){_S(h.needed?"no-hook":"no-hook-false");g||(c||(c=setTimeout(()=>
{b=0;c=null},15E3)),5!=++b||m||(g=!0,_9y(x=>{g=!1;_Pf(e,h.add({answer:x?"Disable notice":"Keep showing"}));_D("noHookConflictMsg",m=x)})))}let b=0,c,g,m=_wk("noHookConflictMsg");return e=>{let h=e.type;delete e.type;if("no-hook-notice"==h)a(h,e);else{if("invalidExtId"==h){if(_ki())return}else if("APDL"==h){if(_to=!0,_7p(e.result))return}else if("NH-error"==h&&3221225477==e.code){_S("segFault");return}_Pf(h,e)}}})(),y=_cy;const z={[_rp]:a=>{let b=_Gr[a.id-_Rd+_Fs];if(b&&(a.trigInstId=b(a.trigInstId),
!a.trigInstId))return;a.mouseGest&&(a.trigInstId=_ds(a.trigInstId,{usePrevMousePos:a.mouseGest}));a.extEvtData&&("tabs"in a.extEvtData&&(a.extEvtData.tabs=_ag(a.extEvtData.tabs)),a.trigInstId=_ds(a.trigInstId,a.extEvtData));_Iy(16777215&a.id-_Rd,a.trigInstId)},[_Se]:a=>_or({joysticksOrder:a.list}),[_1h]:a=>_yi(a.hWnd,a.noEvt),[_Mj]:a=>_Za(a.list),[_zu]:a=>_Lt(a.state?_ms:_nw,_oj[a.hWnd]),[_Nr]:a=>{_Th(_Ro(a));a.noEvt||_Su(_Ta)},[_Cp]:a=>q(a.id,a.params),[_kj]:a=>y(_eu(a.actionType),a.actionSpec),
[_ro]:E,[_fu]:a=>F(a.id,a.type,a.chunk),[_As]:a=>_1i=a.verNum,[_Xd]:a=>{_ik=(_ek=a.exeName.toLowerCase()).replace(/\.[^.]+$/,"");_ek||_Pf("noBrwrName")},[_4r]:_ue,[_Yg]:a=>_c(a.file,"blob")(b=>_Sh(a.callback,b?b.size:_vp)),[_Vo]:a=>{}};let f={},F=(a,b,c)=>{null==f[a]&&(f[a]="list"==b?[]:"",delete f[(a+9)%20+1]);switch(b){case "text":f[a]+=c;break;case "list":f[a].push(...c);break;case "bin":f[a]+=atob(c)}};var _0a=function(a){let b=a&&a.chunkedData;b&&(a=f[b],delete f[b]);return a},_5s=function(a,
b=_cy){_Ya(_Ou,a);b&&(y=b)};let A=function(a,b){b!=d?_Pf("rogueNatHost",{place:"msgLstnr",currPort:typeof d}):(_0p(a)?(b=a[0],a=a[1]):(b=a.msgType,delete a.msgType),(z[b]||_cy)(a))};var _dd=a=>z.add(a),_Fg=(a,b)=>A([a,b],d),_Bh;let d,r,n=0,t={},u=0,v=0,p=100,B=function(a){clearTimeout(r);r=setTimeout(_Xf(),1E3*a)},C;var _Xf=_qf(function*(a){_ta();C=Date.now();d=_Sf.runtime.connectNative(_p[3]+"");d.onMessage.addListener(A);d.onDisconnect.addListener(c=>{c!=d?_Pf("rogueNatHost",{place:"onDisconnect",
currPort:typeof d}):(w(),c.connectSuccess&&(c=Date.now()-_Xs,500>c?n=Math.min(3,n+.5):3E3<c&&(n=0),B(n)),d=null,_Bh=!1)});_h=[];_Fg(_6e);_Vd=null;yield _Fy(p);let b=yield D();if(b){if(b==_2p)p=Math.min(1E3,p+100);else if("NH0fail"==b)++v;else if("notConnected"!=b){if(5==++u){let c=Object.keys(t);1==c.length&&c[0]==_Ap||_Pf("NH-startFail",{lastError:b,allErrors:c})}t[b]=!0}_ta();a&&b.in(_2p,_Ap)?(yield _Fy(800),b=yield _Xf(a-1)):B(Math.min(8,Math.pow(Math.max(u,v)+1,.4)))}else t={},v=u=0,p=100;return!b}),
_ta=function(){clearTimeout(r);d&&(d.disconnect(),w())};let D=_qf(function*(a){86397E3<Date.now()%864E5&&(yield _Fy(3E3));_Rd=Date.now()/864E5|0;l=13625;let b=yield _ky(_Nt,{fileName:_Lh},9E3);if(void 0===b)return"notConnected";if(b==_2p)return b;if(_7p(b))return"NH0fail";d.connectSuccess=!0;_Xs=Date.now();if(b)a||b!=_Da||(yield _Ie("del /Q /F "+_5a),(b=yield _7d(_Lh,yield _ao(_lt,"binary")))||(b=yield D(!0)));else if(_Xj?_o(Date.now()-C):(_Pf("NH-connect"),_O(["LOCAL","natHostInstalled"],_Xj=!0,
0)),l=parseInt(_np.substr(2,3),36),f={},_Ya(_mo,{iTime:_Hp,crVer:_Zo,variant:_3d}),_Fd(),_Bh=!0,yield c=>_Xy()(()=>{_Xa();c()}),_Ya(_uw,{states:_il}),yield c=>_Oi(g=>_Ri(g,c)),_Ya(_iy),!G++&&!_Jr("noStupEvt")){for(let c of["tabs","sess"])_Ie(`forfiles /m *.${c} /d -10 /c "cmd /c del /F /Q @path"`)();_Lt(_og)}return b}),G=0}let _Sh=(l,k)=>_Ya(_qu,{id:l,params:k});
