'use strict';let _4j=_qf(function*(a){_Be(a);_de(a);let d=yield h=>_sd({mouseGest:{},LOCAL:{}},h),e=d.mouseGest||{};_Oh.setEvtLtnrs($("[name=mouseGest]",a)).append(yield _ft(e)).toggleClass("collapsed",_7p(e));$("[syncSettgs]",a).append(_9e(d.LOCAL));$("[installation]",a).css("display",_Ba._Ya(0)?"initial":"none");_Vt&&$("advOpts",a).replaceWith(yield _6g())}),_ft=_qf(function*(a){a||(a={});return _Ww`\n ${_Hk(a.triggers)}\n <hr>\n ${_f(a.params)}\n <p>Try your gestures now. <br> Adjust the parameters to obtain the desired accuracy</p>\n <hr>\n ${_ne(a.display)}\n `});
function _Hk(a={}){return _Ww`\n <div name=triggers value={}>\n <fldGrp>\n <fldWrap>\n Perform with: ${_Mo([..._Ba._mf,["other",{name:"Other"}]].map(([d,e])=>[d,e.name]),a.preset,"preset")} <hw><h h=trig></h></hw>\n </fldWrap>\n ${"other"==a.preset?"<br>":""}\n <fldWrap>\n Timeout: <input type=number name=timeout min=0.2 max=5 step=0.1 value="${a.timeout||1.5}">&nbsp;secs <hw><h h=tOut></h></hw>\n </fldWrap>\n </fldGrp>\n ${"other"==a.preset?_Ww`\n <fldWrap>\n ${_Oh.make(a.begin,"begin",{title:"Begin gesture with: <h h=/gest/bgn></h>",
extraAttrs:"gestureConf noPreconds"})}\n ${_Oh.make(a.end,"end",{title:"End gesture with: <h h=/gest/end></h>",extraAttrs:"gestureConf noPreconds"})}\n </fldWrap>\n `:""}\n &nbsp; &nbsp;\n <precondsWrap>\n ${_Oh.make([{combins:[{eventId:255}],preconds:a.preconds}],"preconds",{extraAttrs:"justPreconds"})}\n <hw><h h=cnd></h></hw>\n </precondsWrap>\n </div>\n `}
function _f(a={}){return`\n <div name=params value={} popupCntr>\n Gesture precision: ${_1u({4:"<i mouseGestDirs></i>4 directions",8:"<i mouseGestDirs=8></i>8 directions"},"dirPrecision",a.dirPrecision||8,"","number")} <hw><h h=dir></h></hw>\n Stroke size: <input type=number name=stepSize value="${a.stepSize||50}" min=5 step=5> <hw><h h=stp></h></hw>\n <!--Sensibility: <input type=number name=dirChangeSens value="${a.dirChangeSens||2}" min=1 max=10> <hw><h></h></hw> -->\n <!--Segment size: <input type=number name=segmentSize value="${a.segmentSize||
6}" min=1 max=30> <hw><h></h></hw> -->\n <button testGestureBegin>Test gestures</button>\n <button testGestureEnd>End gesture test</button>\n </div>\n `}
function _ne(a={}){a.enabled=null==a.enabled?!0:a.enabled;return`\n <div name=display value={}>\n <label>${_Gy("enabled",a.enabled,"hard")}Gesture display</label> <hw><h h=dsp></h></hw>\n <span ${a.enabled?"":"greyedout"}>\n Position:\n ${_Mo({M:"Mouse",W:"Window",S:"Screen"},a.posRef,"posRef")}\n ${_Mo({C:"Center",T:"Top",B:"Bottom"},a.posAnchor,"posAnchor")}\n <hw><h h=pos></h></hw>\n Size: <input type=number name=size value="${a.size||30}" min=10 max=100 step=2> <hw><h h=siz></h></hw>\n Colors: ${_Mo({light:"Light",
dark:"Dark"},a.colors,"colors")} <hw><h h=col></h></hw>\n </span>\n </div>\n `}
function _de(a){let d=new _Wa(_ug(function*(e,h){let k=$("[name=toolbarBtns] TBBtnLst",a).html(""),m=0;for(let b of e){e=_6o(b);var n=_kd(h,b,"icon")||{img:yield _He("tbBtn",e+"","#013379","#ffdc7a")};n=_ig("icon",n,"TBBtn"+b,"tbBtn");k.append(_Ww`\n <TBBtn name=${b}>\n <t>Button ${e}</t>\n Icon: ${n}\n <input type=text name=title value="${_kd(h,b,"title")}" placeholder="Optional title..." autocomplete=off>\n <del button title="Remove"></del>\n </TBBtn>\n ${++m%2?"":"<br>"}\n `);_kd(h,b,"icon")||
n.triggerEvt("change",!0)}}));_Jf()(d.onReady());_Mt("toolbarBtns")(d.onReady())}
function _9e(a){let d={"":"Off",true:"On"};80<=_Zo&&(d.compress="On (compressed)");a=$(`\n <div><l>Local synchronization:</l> ${_Mo({"":"Off",sameBrwr:"Across same browser",allBrwr:"Across all browsers"},a.localSync,"localSync")} <h h=loc></h></div>\n <hr b=4>\n <div><l>Remote synchronization:</l> <c ilnBlk>${_Mo(d,a.remoteSync,"remoteSync")} <usg></usg> </c> <h h=rem></h></div>\n `);_Nh($("[name=remoteSync]",a)[0]);return a}
let _Nh=_ug(function*(a){const d=_Sf.storage.sync;let e=100*(yield k=>d.getBytesInUse(k))/d.QUOTA_BYTES|0,h=a.value?`${e}% of ${_nk(d.QUOTA_BYTES)}B`:"";$(a).next().attr("lvl",89<e?"high":75<e?"med":"low").html(h)}),_Jy=_qf(function*(a,d){var e=yield _Mt("trigActList","length");let h=_kd(a,"trigActList","length");if(e&&h){var k=JSON.stringify(yield _gs())==JSON.stringify(a);if(!k)var m=yield _Wg(_Ze("confirmSettgsOvrwrt"),{width:"initial"})}if(k)return"sameSettgs";e="cancel"==m;if(!e)if(h&&"useCurr"!=
m)e=!(yield _wy(a));else return"currSettgs";e&&(d.value="",$(d).triggerEvt("change",!0))}),_6g=_qf(function*(){let a=yield _Mt("advOpts");return $(`\n <section name=${"advOpts"} helpCtx=advOpts class=${a?"":"collapsed"}><h1>Advanced Options <btn></btn></h1>\n ${yield _Cj(a)}\n </section>\n `)[0]}),_Cj=_qf(function*(a){a={dfltWldcrd:_go,ignInjInp:"no",trigRepTime:.6,trigStepTime:1.5}.add(a);let d=[[_go,"No wildcard"],[_hi,"On other devices (*)"],[_lo,"On any device (**)"]],e=yield k=>_Sf.extension.isAllowedIncognitoAccess(k),
h=_Xr;return`\n <div><l>Trigger's default wildcard:</l> ${_Mo(d,a.dfltWldcrd,"dfltWldcrd","number")} <h h=wldcrd></h></div>\n <hr>\n <div><l>Ignore synthetic input:</l> ${_Mo({no:"Don't ignore",kbd:"Ignore from keyboard",mse:"Ignore from mouse",all:"Ignore all"},a.ignInjInp,"ignInjInp")} <h h=ignInj></h></div>\n <hr>\n <div tight><l>Trigger repetition timeout:</l> <input type=number name=trigRepTime value=${a.trigRepTime} min=0.1 max=5 step=0.1> &nbsp;secs &nbsp; <h h=repTm></h></div>\n <div><l>Trigger steps timeout:</l> <input type=number name=trigStepTime value=${a.trigStepTime} min=0.1 max=5 step=0.1> &nbsp;secs &nbsp; <h h=stpTm></h></div>\n <hr>\n <div externOpt>\n <st ${h?
"on":"off"}></st>\n <cptn>Local page access is ${h?"ON":"OFF"}</cptn> <h h=fileAcc></h> <br>\n Turn it ${h?"off":"on"} in <a href="${_xg.fileAcc}">this page</a>.\n </div>\n <div externOpt>\n <st ${e?"on":"off"}></st>\n <cptn>Incognito access is ${e?"ON":"OFF"}</cptn> <h h=incgAcc></h> <br>\n Turn it ${e?"off":"on"} in <a href="${_xg.incogAcc}">this page</a>.\n </div>\n `});const _rj=new _qy;
function _Be(a){function d(b){"TBBtnInit"==b&&(e(),_de(a),n=!1)}function e(){_Sf.runtime.onMessageExternal.removeListener(d);_Sf.windows.remove(m||0,_pd)}_dj("mouseGest.triggers.preset",(b,c)=>{$("[name=triggers]",a).replaceWith(_Hk(_kd(b,...c.slice(0,-1))));_rt(b)});_dj("mouseGest.display.enabled",(b,c)=>{$("[name=display]",a).replaceWith(_ne(_kd(b,...c.slice(0,-1))))});_dj("toolbarBtns.*",(b,c)=>{_hw(+c[c.length-1],_kd(b,...c))});let h,k;_dj("mouseGest.params",(b,c)=>{let f=$("#gestureTestBoard > polyline")[0];
f&&f.points.length&&setTimeout(()=>{_Ba._Ya(_qe,!1);k=2;_Ba._Ya(_qe,_sa(f.points[0]));for(let g=1;g<f.points.length;++g)_Ba._Ya(_5t,_sa(f.points[g]));_Ba._Ya(_qe,!1)})});let m,n=!0;$(a).on("click","[installTbBtn]",function(){e();let b=$(this).closest("section").find("TBBtn");for(var c=0;c<_Te.length&&(b.filter(`[name=${c}]`)[0]||c.in(1,2,3,4));++c);let f=_Te[c];f?_Vt?_O(["toolbarBtns",c+""],{},0,()=>_de(a)):_2(_Ze("addTBBtnMsg",{attrs:n?"":"noReason"}),{width:"initial"},()=>{_Sf.windows.create({url:_xg.chromeWS+
f+"/overview",focused:!0,type:"popup",left:_pa+(innerWidth-1040)/2|0,top:_s+(innerHeight-680)/2|0,width:1040,height:680},g=>{m=g.id;_Sf.runtime.onMessageExternal.addListener(d)})}):_2(_Ze("noMoreTBBtns",{maxBtns:_Te.length}),{width:"initial"})}).on("click","[testGestureBegin]",function(){let b=$("<svg id=gestureTestBoard><g></g><polyline/></svg>").appendTo("body")[0],c=b.firstElementChild,f=b.lastElementChild;$(this).closest("[name=params]").addClass("testGesture");$(window).on("mousemove.gestureTest",
function(g){h&&!k&&(_Ba._Ya(_5t,{x:g.originalEvent.screenX,y:g.originalEvent.screenY}),_Mg(f,_zf,_Xg))}).on("focus.gestureTest blur.gestureTest",g=>_Ba._5s("focus"==g.type?{mouseGest:_xs("B")}:!1,null));_Ba._5s({mouseGest:_xs("B")},(g,l)=>{if(l.state==_xs("I"))h=!0,k&&--k||_Mg(f,_zf,_Xg,!0),c.innerHTML="";else if(l.state==_xs("S"))h=!1;else{g=_b(l.len,10,100);let p=_zi(l);l=45*(_eu(l.dir)-1);c.insertAdjacentHTML("beforeend",`<path d="M-7,7 L0,0 L7,7 M0,5 L0,${g}" transform="translate(${p.x} ${p.y-
g}) rotate(${l} 0 ${g})"/>`)}})}).on("click","[testGestureEnd]",function(){$("#gestureTestBoard").remove();$(this).closest("[name=params]").removeClass("testGesture");$(window).off(".gestureTest");_Ba._5s(!1);h=!1}).on("dblclick","TBBtn del",function(){_O(_fw(this),void 0,0,()=>_de(a))}).on("click","section > h1 btn",_ug(function*(){let b=$(this).closest("section");if(b.hasClass("collapsed")){let c={mouseGest:_ft,advOpts:_Cj},f=b.attr("name");$("> :not(h1)",b).remove();b.append(yield c[f](yield _Mt(f)))}else _O(_fw(this),
null,0);b.toggleClass("collapsed")})).on("change","[name=localSync]",_ug(function*(){if(this.value){let b="sameBrwr"==this.value;_rj.clear();yield _rj.wait();let c=yield _Ba._ke(b);if(yield _Jy(c,this))yield _Xk("add"),yield _Ba._Ei(b)}else yield _Xk("del");_Ba._xj(this.value)})).on("change","[name=remoteSync]",_ug(function*(b,c){if(this.value&&"dontSync"!=c){yield _Ba._3f();let [g,l]=yield _Ba._0i();var f=yield _Jy(g,this);80<=_Zo&&!f&&l&&"true"==this.value&&(this.value="compress",$(this).triggerEvt({change:"dontSync"},
!0))}_Ba._xk(this.value);("currSettgs"==f||"sameSettgs"==f)&&(b=yield _Ba._fi())&&b.size>b.quota&&(_2(`\n Your settings require <b>${_nk(b.size,4)}B</b> of storage which exceeds the maximum of <b>${_nk(b.quota)}B</b>\n allowed by your browser's sync service. <hr b=2>\n Remote synchronization won't be possible. ${"compress"==this.value?"":'Try enabling "compressed" mode.'}\n `,{type:"warning"}),this.value="",$(this).triggerEvt("change",!0));_Nh(this)})).on("click","[exportToFile]",()=>{let b=`${_Qk.alias} settings (${_Eg(new Date,
"Y-M-D")}).${_ia}`;_er(c=>_Xu(b,JSON.stringify(c)))}).on("click","[importFromFile]",_ug(function*(){let b=yield _Bf(_ye,"text");_fe(b)})).on("click","[openSttgsFile]",_ug(function*(){let b=yield _Js("",_ny);b&&_Po(b)})).on("click","[uninstall]",()=>_3h()).on("click","advOpts",_ug(function*(){let b=yield _6g();b.style.cssText="opacity: 0; transform: scaleY(0); ";$(this).replaceWith(b);b.scrollIntoView({behavior:"smooth"});yield c=>_Oa(c);b.style.cssText="transform-origin: top; transition: 0.6s"})).on("change",
function(b){if(!$(b.target).parent().closest("[DataModule]")[0]){let c=_fw(b.target),f=c.join("."),g=_Me(b.target);"mouseGest.triggers.preconds"==f&&(g=g[0].preconds);b="advOpts"==c[0]||f.endsWith(".timeout")||$(b.target).is("triggers")||f.startsWith("mouseGest.display.")&&!f.endsWith(".enabled")?400:0;_O(c,g,b,()=>_rj.send())}})}
let _3h=_ug(function*(){if(_Ba._Ya(0)){if(yield _Dg("","\n Once the native component is uninstalled, the extension will no longer work. <hr b=2>\n To make it work again, you'll have to re-install the native component by <br> reloading this page. <hr b=2>\n Do you want to uninstall now?\n ",{width:"initial"})){_1w();var a=yield _Ba._Ie("dir /B *.exe",".",!0);a=[...new Set(a.stdout.trim().split(/\n+/))].map(d=>{d=(d.match(/^[a-z]+/i)||[])[0];return"AutoCtrl"!=d?_kd(_Cw,d,"name"):""}).filter(d=>d);if(a.length&&
(_1w(!1),!(yield _Dg("",`\n The native component is also being used by the following extensions: <hr b=2>\n ${a.map(d=>`<li><b>${d}</b></li>`).join("")} <hr b=4>\n If you uninstall now, those extensions will stop working too. <hr b=2>\n Continue?\n `,{yes:"Yes, uninstall anyway",no:"Cancel",icon:"info"}))))return;_1w();a=`"%tmp%\\${_pr}"`;yield _Ba._Ie(`copy /Y ${_Vg} /B ${a} && cd .. && ${a} /noConfirm | more & del /F /Q ${a}`);setTimeout(()=>_1w(!1),2E3)}}else _2("The native component is not installed.",
{type:"error"})});
