'use strict';function _tr(m){return _vg(m,!1,!0)}
let _Ch=(()=>{function m(a,b,d){function c(h){let k=_Np(h,"action");h==a&&(e=f,g=k.grp);return`<item value=${h} ${h==a?"selected":""} ${k.perms?`perms="${k.perms}"`:""}>${k.name} ${k.h?`<h h=${h}/_></h>`:""}</item>`}let f,e=b?"adv":"basic",g;b=$(`\n <actionSelector DataModule ${b?"noBasic":""} helpCtx=actList>\n <content>\n <pane ${f="basic"}>\n <cont>\n <column>\n ${c("goBack")} ${c("goForward")} ${c("reload")} ${c("zoomIn")} ${c("zoomOut")}<hr>\n ${c("pin")} ${c("mute")} ${c("duplicate")} ${c("detach")} <hr>\n ${c("openNTP")} ${c("openElemUrl")} ${c("saveElemUrl")}\n </column>\n <column>\n ${d?"<item>No action</item> <hr>":
""}\n ${c("switchPrev")} ${c("switchLeft")} ${c("switchRight")}\n ${c("switchLeftmost")} ${c("switchRightmost")}\n <hr>\n ${c("close")} ${c("closeLefts")} ${c("closeRights")}\n ${c("closeOther")} ${c("closeWin")}\n <hr>\n ${c("reopen")}\n </column>\n </cont>\n </pane>\n <pane ${f="adv"}>\n <groups>\n ${[...n].map(([h,k])=>`<it grp=${h}>${k.name} <h h=${k.h||""}></h></it>`).join("")}\n </groups>\n <conts>\n ${[...n].map(([h,k])=>`<it ${h}>${k.members.map(c).join("")}</it>`).join("")}\n </conts>\n </pane>\n </content>\n <tabs>\n <tab pane=basic>Basic Actions</tab>\n <tab pane=adv>Advanced Actions</tab>\n </tabs>\n </actionSelector>\n `).on("click",
"item",function(h){$(h.delegateTarget).triggerEvt({itemSelect:$(this).attr("value")});$(this).triggerEvt("focusLost",!0)}).on("mousedown","tab",function(h){$(`> content > [${$(this).attr("pane")}]`,h.delegateTarget).add(this).attr("selected","").siblings().attr("selected",null)}).on("mousedown","groups > it",function(){$(this).closest("pane").find(`it[${$(this).attr("grp")}]`).add(this).attr("selected","").siblings().attr("selected",null)});$(`[pane=${e}]`,b).trigger("mousedown");$(`[grp=${g||"tab"}]`,
b).trigger("mousedown");return b}function v(a,b){let d=$("[name=action]",a).attr("value"),c=m(d,0<_Zg(a),!!b).on("itemSelect",function(f,e){if(d!=e){f=$(a).closest("action").find("[name=targets]");!f.is(":visible")&&$(a).closest("trigAct").find("combinSeq:first event:last").hasClass("mouse")&&_3k(f[0],"hoveredTabs");let g=p({action:e,params:{}});$(a).replaceWith(g);_Yo(g);q(g);_Or(d,"setSwtchSt","brkActSeq")&&_Pj(800);"openMenu"==d&&_nf(800);w.paramsGuiGen[e]&&setTimeout(()=>g.find(">l").triggerEvt({mousedown:!0},
!0),300)}else if(!e){let g=a.closest("content");setTimeout(()=>{_aw("\n <help>Leave this field empty if you want to disable a shortcut. <hr b> i.e. the trigger will fire no action.</help>\n ",$("actionStep > fld",g),"rbtl","helpBubble","","opacity")},100)}}).on("focusLost",()=>{$(a).is(":visible")&&!$(a).attr("value")&&x(a)}).on("DOMInserted",function(){var f=$("h",a);if("visible"==f.css("visibility")){let g=f[0].getBoundingClientRect();var e="/"+_Cg(f.attr("h"),_ka(f)).join("/");f=f.clone().attr("h",
e).css({position:"absolute",margin:0}).appendTo(c);f[0].offsetParent&&(e=f[0].offsetParent.getBoundingClientRect(),f.css({left:g.left-e.left,top:g.top-e.top}))}});_aw(c,a,"btrl ,VR","tailOnly noTail");$("item[selected]",c).each(function(){this.scrollIntoViewIfNeeded(!0)})}function A(a){var b=$(a).attr("value");let d=0,c="";for(let f of _ea("tse",!0))c+=`${++d%2?"<tr customTse>":""}<td>${_ya("tse",f,b)}`;b=$(`\n <targetSelector popupCntr DataModule>\n <scrollWrap>\n <table><tr>\n <td>\n ${_ya("tse",
"currentTab",b)}\n ${_ya("tse","newestTab",b)}\n ${_ya("tse","openerTab",b)}\n ${_ya("tse","eventTabs",b)}\n ${_ya("tse","hoveredTabs",b)}\n <hr>\n ${_ya("tse","leftTab",b)}\n ${_ya("tse","allLeftTabs",b)}\n ${_ya("tse","firstTab",b)}\n <hr>\n ${_ya("tse","prevUsedTab",b)}\n ${_ya("tse","prevUsedTabAnyWin",b)}\n ${_ya("tse","nextUsedTab",b)}\n ${_ya("tse","nextUsedTabAnyWin",b)}\n </td><td>\n ${_ya("tse","activeTabs",b)}\n ${_ya("tse","highlighted",b)}\n ${_ya("tse","pinnedTabs",b)}\n ${_ya("tse",
"audibleTabs",b)}\n ${_ya("tse","nonMinimTabs",b)}\n <hr>\n ${_ya("tse","rightTab",b)}\n ${_ya("tse","allRightTabs",b)}\n ${_ya("tse","lastTab",b)}\n <hr>\n ${_ya("tse","otherTabs",b)}\n ${_ya("tse","otherTabsAllWins",b)}\n ${_ya("tse","currWinTabs",b)}\n ${_ya("tse","allTabs",b)}\n </td> \n ${c}\n </table>\n </scrollWrap>\n <newEntity type=tse>Choose more tabs...</newEntity>\n </targetSelector>\n `);return _Oj(b,a)}function y(a){let {action:b,params:d={}}=a;if(b.in("undoClose","selectMarkedItem",
"runScript"))return!0;if(b.in("loadUrls","openBookmarks"))return!!d.tabPos;a=_3p(b,d);if("object"==typeof a&&a[0]){var c;if(!(c=1<a.length||a[0].targets))a:{a=a[0].sequence;for(let f of a)if(y(f)){c=!0;break a}c=!1}return c}return!1}function B(a){let {action:b,params:d={}}=a;if(b.in("undoClose","openMenu","closeMenu","moveSelectMark","selectMarkedItem","stopSendInput","clpbrdCut","clpbrdCopy","clpbrdPaste","copyLinks","extractURLs","delDupLines","copyElemUrl","setSwtchSt","setVolume","setMonBright",
"setMonPower","screenSaver","showDesktop"))return!1;switch(b){case "loadUrls":return!d.tabPos||d.usesTabs;case "openBookmarks":return!d.tabPos;case "clpbrdPut":case "insertText":return d.usesTabs&&!d.verbatim;case "runCommand":return d.usesTabs;case "saveUrl":return d.usesTabs;case "txtToUrl":return d.usesTabs;case "playAudio":return d.usesTabs;case "scrollWins":return!d.pointedElem;case "sendInput":return d.intoPage;case "runScript":return!d.bkgrnd;case "wait":return+d.event<_Qu;case "brkActSeq":return(d.conds||
[]).some(c=>"tgtTabs"==c.type||c.usesTabs);case "bookmarkUrls":return d.usesTabs}a=_3p(b,d);return"object"==typeof a?a[0]&&null==a[0].targets&&r(a[0].sequence):!0}function r(a=[]){let b=!1;for(let d of a){if(B(d)&&!b)return!0;b||(b=y(d))}return!1}function t(a){let b=C[a.action],d=_Np(a.action,"action").name;return b&&!_7p(a.params)&&(b(a.params)||"").replace("\v",d)||d}function z(a,b){a=$(`actionStep > [entId='${a}']`);a.length&&a.html(t(_Me(b||a.first().parent()[0])))}function p(a,b=!0){return a?
_Ww(_ga)`\n <actionStep value={}>\n <l name=action value=${a.action} ${"runScript"==a.action?`entId=${a.params.scriptId}`:""}>${t(a)}</l><b></b>\n <par name=params value=$${a.params}></par>\n </actionStep>\n `:$(`<actionStep><fld>Choose an action</fld>${b?"<h h=selAct></h>":""}</actionStep>`)}function u(a){a=a||{};return _Ww`\n <action value={}>\n <actSeq name=sequence value=[] needsTgtTabs=${r(a.sequence)}>\n ${(_7p(a.sequence)?[null]:a.sequence).map(b=>[p(b),"<sep button actBtn hh=newStp></sep>"])}\n </actSeq>\n <targets>\n Apply to: ${_Ws("tse",
"targets",a.targets||"currentTab")} <h h=tgtsFld></h>\n </targets>\n <ctrl>\n <del button title="Delete this action chain">&#xD7;</del>\n <move button up title="Move up">&#x25B4;</move>\n <move button down title="Move down">&#x25BE;</move>\n </ctrl>\n </action>\n `}function x(a){$(a).closest("action").replaceWith(u(_vg(a.closest("action"))))}function q(a){var b=r(_vg(a.closest("action")).sequence);a=$(a).closest("actSeq").attr("needsTgtTabs",b);b||(b=a.closest("action").find("[name=targets]"),_Tp(b.attr("value"))&&
_3k(b[0],"currentTab"))}const w=document.currentScript.parentElement,n={tab:{name:"Tab Actions"},win:{name:"Window Actions",h:"../winAct2"},bmrk:{name:"Bookmark Actions"},menu:{name:"Menu Actions",h:"../menu"},clbrd:{name:"Clipboard Actions",h:"/clpbrd"},sys:{name:"System Actions"},exec:{name:"Execution Control"},other:{name:"Other"}};for(let [a,b]of _Ba._tt.action)b.grp&&_ng(n[b.grp],"members",[]).push(a);const l=a=>({[_Hj]:"Un\v",[_Fa]:"Toggle \v"})[a.mode],C={activateTabs:a=>a.peek&&"Peek tabs",
highlightTabs:l,muteTabs:l,pinTabs:l,zoomTabs:a=>0<a.type?"Zoom in tabs":0>a.type?"Zoom out tabs":Number.isNaN(+a.type)?null:"Reset tabs zoom",focusWin:l,minimizeWins:l,maximizeWins:l,fullscreenWins:a=>({[_Hj]:"Exit \v",[_Fa]:"Toggle \v"})[a.mode],hideWins:l,topmostWins:a=>({[_Ns]:"Set",[_Hj]:"Unset",[_Fa]:"Toggle"})[a.mode]+" topmost",scrollWins:a=>"Scroll "+a.dir,moveSelectMark:a=>0>a.dir?"\v back":"\v fwd.",openElemUrl:a=>"Open "+{lnk:"Link",mda:"Media"}[a.type]+" URL",setVolume:a=>({up:"Increase",
down:"Decrease",toggle:"Toggle mute"}[a.mode]||a.mode)+" volume",setMonBright:a=>({up:"Increase",down:"Decrease"}[a.mode]||a.mode)+" brightness",brkActSeq:a=>("stopChn"==a.action?"Stop chain":"stopSeq"==a.action?"Stop entire seq":"Continue chain")+(_7p(a.conds)?"":" if"),wait:a=>"time"==a.event?"\v time":"\v event",setSwtchSt:a=>1==a.state?"Set switch ON":0==a.state?"Set switch OFF":"Toggle switch",runScript:a=>(a=_Np(a.scriptId,"script").name)&&`<c>\v:</c><d>${a}</d>`,groupTabs:a=>"no"==a.target?
"Un\v":"\v"};let D=_qf(function*(a){function b(){const e=0==$(a).prevAll(a.tagName).length,g=0==$(a).nextAll(a.tagName).length,h="object"==typeof _Np(d.action,"action").value;return e&&g||h?null:e?"first":g?"last":"middle"}let d=_vg(a),c=$(`\n <optPane actStep=${d.action} DataModule value={} helpCtx="actList/${d.action}">\n <noParams>No settings for<br> this action</noParams>\n <div actions><btn dir=lft title="Move action to the left">&lt;</btn><btn del>Delete action</btn><btn dir=rgt title="Move action to the right">&gt;</btn></div>\n </optPane>\n `).attr("pos",
b()).on("dblclick","btn[del]",function(){_sy($(this).closest("optPane"))&&_Pj(500);"openMenu"==d.action&&_nf(500);let e=a.closest("action");$(this).triggerEvt("focusLost",!0);a.remove();_Yo(e);x(e)}).on("click","btn[dir]",function(){var e=$(this).attr("dir");e=$(a)["lft"==e?"prevAll":"nextAll"](a.tagName).first();var g=e.find("> l").attr("value");"object"==typeof _Np(g,"action").value?(g=_Np(g,"action").name,_aw(`\n <help noPopupAround>\n <act>${g}</act> is a <b>basic action</b>, it cannot be moved. <hr b> Basic actions can only be the first step of an action chain.\n Following <br> steps must be <b>advanced actions</b> only. <hr b>\n You can use an <a href='${_xg.actions}#sequence'>unchained sequence</a> instead, to put basic actions in <br> any position.\n </help>\n `,
e,"ltbr","helpBubble big","","opacity")):(g=a.nextElementSibling,e.after(a),$(g).before(e),c.attr("pos",b()).triggerEvt({resize:!0},!0),q(a),_Yo(a))}).on("change input",_F(250,function(e){if(!$(e.target).closest("[DataModule]",this)[0]&&document.contains(this)){$("[name=params]",a)[0].value=_wf(_tr(this));e=$("> l",a);var g=e.attr("entId");g?z(g,a):e.html(t(_Me(a)));q(a);_Yo(this)}}));var f=w.paramsGuiGen[d.action];if(f){f=f({params:{}}.add(d),c[0]);"function"==typeof f&&(f=yield f);let e=(f instanceof
jQuery?f[0]:f).onInsert;$("noParams",c).replaceWith(f);e&&(c.appendTo("hiddenDoc"),e())}return c});return{make:function(a=[],b=""){return _Ww`\n <actions trigOrAct DataModule popupCntr helpCtx ${_7p(a)?"class=empty":""} name="${b}" value=[]>\n <header>Action <selector><add button actBtn hh=addAct></add></selector></header>\n <content>${(a.length?a:[null]).map(u)}</content>\n </actions>\n `},setEvtLtnrs:function(a){$(a).attr("optionsCollection","").on("mousedown","actionStep > l:not(.popup)",function(b,
d){D(this.closest("actionStep"))(c=>{_aw(c,this,"btrl ,AO","tailOnly noTail");d&&c.triggerEvt("change")})}).on("mousedown","actSeq > actionStep:not([value])",function(){v(this,$(this).closest("action").is(":only-of-type"))}).on("click","actSeq > sep",function(){$(this).after(p(null,!1),"<sep></sep>");setTimeout(()=>$("~ actionStep:not([value])",this).first().triggerEvt("mousedown",!0),200)}).on("mousedown","actionStep > b",function(){v($(this).closest("actionStep")[0])}).on("mousedown","action > targets customSelect",
function(){let b=A(this).on("focusLost",function(){$(this).triggerEvt("close").remove()});_aw(b,this,"blrt ,VR");$("item[selected]",b).each(function(){this.scrollIntoViewIfNeeded(!0)});return!1}).on("change","action > targets customSelect",function(){_Yo(this)}).on("click","actions > header add",function(){let b=$(this).closest("actions");$("action:last-of-type actionStep[value]",b)[0]&&b.find("> content").append(u())}).on("dblclick","action > ctrl del",function(){let b=$(this).closest("action");
b.find("[value=openMenu]")[0]&&_nf(500);b.find("[value=brkActSeq], [value=setSwtchSt]")[0]&&_Pj(500);let d=this.closest("actions");b.remove();_Yo(d)}).on("click","action > ctrl move",function(){_Ey(this.closest("action"),$(this).is("[down]")?1:-1,400);_Yo(this)}).on("change","actions",function(){$(this).toggleClass("empty",!$("sep:visible",this).length)})},updActLbl:z}})();
