'use strict';function _sd(a,b,k=_Sf){k.storage.local.get(a,g=>{setTimeout(()=>b(_my(g||_wf(a)||{})))})}function _or(a,b){_Sf.storage.local.set(_Mk(a),()=>{b&&setTimeout(b)})}function _Mk(a){a=a.sc();"trigActList"in a&&(a.trigActList=a.trigActList.toJSON());if("customEntities"in a){a.customEntities=a.customEntities.sc();for(let b in a.customEntities)a.customEntities[b]=[...a.customEntities[b]]}return a}
function _my(a){"trigActList"in a&&(a.trigActList=_Eh(a.trigActList));if("customEntities"in a)for(let b in a.customEntities)a.customEntities[b]={}.add(a.customEntities[b]);return a}function _Du(a,b,k){a=a.sc().del(Object.keys(b));_7p(a)?k(b):_sd(a,g=>k(g.add(b)))}let _Mt=(...a)=>b=>{_sd({[a[0]]:null},k=>b(_kd(k,...a)))};
{let a={},b=Symbol(),k=Symbol();var _dj=function(...l){let q=l.pop();for(let n of l)"string"==typeof n&&(n=n.split(".")),l=""===n.slice(-1)[0]?(n.pop(),b):k,_ng(a,...n,l,[]).add(q)},_By=function(...l){l[l.length-1].runOnce=!0;return _dj(...l)},_7s=function(...l){l[l.length-1].grpChng=-1;return _dj(...l)};let g=function(l){function q(r,p,w){if(r){r[k]&&n.push({funcs:r[k],path:p});r[b]&&0==w.length&&n.push({funcs:r[b],path:p});p=p.concat(w.slice(0,1));let c=w.slice(1);q(r["*"],p,c);q(r[w[0]],p,c)}}
let n=[];q(a,[],l);return n},m,v=[],x=0;var _O=function(l,q,n=300,r){clearTimeout(m);v.push({keyPath:_3g(l),value:q,callback:r});m=setTimeout(()=>{let p=v;v=[];let w={};for(let c of p)w[c.keyPath[0]]=null;++x;_sd(w,c=>{for(let e of p)_ng(c,...e.keyPath,e.value,NaN);_or(c,()=>{const e=_pd();let d={};for(let h of p){if(!e){var f=g(h.keyPath);for(let t of f){f=t.funcs;const y=_ng(d,t.path.join(),[]);for(let z=f.length;z--;){const u=f[z];u.grpChng?u.grpChng!=x&&(u.grpChng=x,u(c,t.path)):u.runOnce?(f.splice(z,
1),u(c,t.path)):0>y.indexOf(u)&&(y.push(u),u(c,t.path))}}}h.callback&&setTimeout(()=>h.callback(e))}})})},n)}}
let _Ca=(a,b=0)=>(k=_cy)=>{let g=new _Wa;for(let [m,v]of a)_O(m.split("."),v,b,g.onReady());g.setCallback((...m)=>{m=m.filter(v=>v)[0];k(m)})},_gs=()=>a=>_Sf.storage.local.get(null,b=>a(b.del("LOCAL"))),_wy=_qf(function*(a){var b=window==_Ba;if(b||(yield _Ih(_Og(a),"permMsgs/newSttgs"))){var k=yield g=>_sd({LOCAL:{}},g);yield g=>_Sf.storage.local.clear(g);yield g=>_Sf.storage.local.set(a.add(k),g);if(_pd())b||_2("ERROR: \n\n"+_pd(),{type:"error"});else{yield g=>_Ba._xi(g);if(b){(yield g=>_8j(a,g))||
_Sf.permissions.remove({permissions:["background"]});b=yield _Ge({url:_Sf.runtime.getURL(_ce)});for(let g of b)_Sf.tabs.reload(g.id)}else _Rs("New settings imported successfully. <hr b=3> Reloading now...",1200).onHide(()=>location.href="");return!0}}}),_Ty=_qf(function*(a){_Ba._Rh&&(yield _Xk("set",a));yield _wy(a)});function _ir(a){for(let [b,k]of _Ki(a))_ir(k),_7p(k)&&(_0p(a)?a.splice(b,1):k&&"object"==typeof k&&"value"==b&&a.name||delete a[b]);return a}
let _gg=_qf(function*(){if((yield _Mt("trigActList")).length||!_7p(_ir(yield _Mt("customEntities"))))return!1;let a=_ir(yield _Mt("mouseGest"));return!_kd(a,"triggers","preconds")&&(!_kd(a,"triggers","begin")&&!_kd(a,"triggers","end")||"other"!=_kd(a,"triggers","preset"))});
function _jd(a,b,k,g){function m(c,e){for(let d=1;;++d)if(!(d in c||d in e))return d}function v(c,e,d){c.trigActList.del(e);for(let [f,h,t]of _2t(c.customEntities.menuSpec))"type"==f&&"action"==h&&t.content==e&&(t.content=+d)}function x(c,e,d,f,h){h||(c.customEntities[e][f]=c.customEntities[e][d]);delete c.customEntities[e][d];d=e+":"+d;e=e+":"+f;e=JSON.stringify(_Mk(c)).replace(RegExp(`"${d}"`,"g"),`"${e}"`);c.add(_my(JSON.parse(e)))}function l(c,e){return 0==_ck(_Xe(c),_Xe(e))}function q(c,e){return JSON.stringify(e).replace(/"([a-z]+):(\d+)"/ig,
(d,f,h)=>(f=_kd(c.customEntities[f],h,"value"))?'"'+q(c,f)+'"':d)}function n(c,e){return q(a,c)==q(b,e)}function r(){do{var c=!1;for(let e of Object.keys(b.trigActList)){let d=b.trigActList[e];for(let [f,h]of a.trigActList)!d.disabled&&h.disabled||h.title&&d.title&&!l(h.title,d.title)||!n([h.triggers,h.actions],[d.triggers,d.actions])||(c=!0,v(b,e,f),!h.title&&d.title&&(h.title=d.title),!h.icon&&d.icon&&(h.icon=d.icon))}}while(c)}function p(c,e,d){for(let [,f]of d)f.sctnId==c.id&&(f.sctnId=e);c.id=
e}function w(){for(let [c,e]of _Ki(b.sections))for(let d of a.sections)l(e.name,d.name)&&(p(e,d.id,b.trigActList),b.sections.splice(c,1))}for(let [,c]of a)_ir(c);for(let [,c]of b)_ir(c);(function(){for(let [c,e]of b.trigActList)if(a.trigActList.has(c)){let d=m(b.trigActList,a.trigActList);b.trigActList.set(d,e,b.trigActList.getPos(c));v(b,c,d)}})();(function(){a:for(;;){for(let [e,d]of b.customEntities)for(let [f]of d){var c=a.customEntities[e]||{};if(f in c){c=m(d,c);x(b,e,f,c);continue a}}break}})();
g&&r();(function(){a:for(;;){for(let [c,e]of b.customEntities)for(let [d,f]of e)if(f.name)for(let [h,t]of a.customEntities[c]||{})if(l(f.name,t.name)){if(n(t.value,f.value))x(b,c,d,h,!0);else{let y=f.name.replace(/\((\d+)\)$/,(z,u)=>`(${+u+1})`);l(y,f.name)&&(y=f.name+" (2)");b.customEntities[c][d].name=y}continue a}break}})();(function(){let c=b.sections.reduce((d,f,h)=>(d[f.id]=h,d),{}),e=a.sections.reduce((d,f,h)=>(d[f.id]=h,d),{});for(let d of b.sections)if(d.id in e){let f=m(c,e);p(d,f,b.trigActList)}})();
k&&w()}function _ur(a,b,k=!1){a.trigActList=k?b.trigActList.add(a.trigActList):a.trigActList.add(b.trigActList);a.sections.push(...b.sections);for(let [g,m]of b.customEntities)_ng(a.customEntities,g).add(m);for(let [g,m]of b.toolbarBtns)_kd(a.toolbarBtns[g],"icon","img")||(a.toolbarBtns[g]=m);return a};
